marklogic/marklogic-spark-connector

- CONTRIBUTING.md
- build.gradle
- src/main/java/com/marklogic/spark/DefaultSource.java
- src/main/java/com/marklogic/spark/MarkLogicTable.java
- src/main/java/com/marklogic/spark/reader/MarkLogicPartitionReader.java
- src/main/java/com/marklogic/spark/reader/MarkLogicScanBuilder.java
- src/main/java/com/marklogic/spark/reader/ReadContext.java
- src/test/java/com/marklogic/spark/AbstractIntegrationTest.java
- src/test/java/com/marklogic/spark/reader/PerformanceTester.java
Had to move some things around:
- Moved MarkLogicTableProvider to `com.marklogic.spark` and renamed it `DefaultSource` to follow the Spark 2 convention, which PySpark seems to rely on.
- Renamed `MarkLogicReader` to `MarkLogicTable` as we'll be adding "write" support to that soon.
- Added details to the CONTRIB file on how to use PySpark.
> DEVEXP-386 Can now use connector in PySpark

- build.gradle
- src/main/java/com/marklogic/spark/MarkLogicTable.java
- src/main/java/com/marklogic/spark/reader/HostUtil.java
- src/main/java/com/marklogic/spark/reader/MarkLogicPartitionReader.java
- src/main/java/com/marklogic/spark/reader/MarkLogicPartitionReaderFactory.java
- src/test/java/com/marklogic/spark/reader/GetDataHostsTest.java
I wrote up DEVEXP-406 to address what happens when a particular host stops working; DMSDK has support for that - i.e. that client is removed and not used again. 
To fully test this, we need a multi-node cluster, and ideally with at least 1 node not having a forest for the database. That will be addressed in a follow-up PR that adds a docker-compose file for building such a cluster and doing manual testing with it.
> DEVEXP-378 Now using multiple hosts in a cluster

- src/main/java/com/marklogic/spark/reader/MarkLogicPartitionReader.java
- src/main/java/com/marklogic/spark/reader/PlanAnalyzer.java
- src/test/java/com/marklogic/spark/AbstractIntegrationTest.java
- src/test/java/com/marklogic/spark/reader/ReadRowsWithAllSparkDataTypesTest.java
- src/test/java/com/marklogic/spark/reader/ReadRowsWithInferredSchemaTest.java
Turns out we didn't need any code changes, but added tests to verify that `spark.sql.session.timeZone` works as expected in our connector.
> DEVEXP-388: Verifying that Spark timeZone property works

- src/main/java/com/marklogic/spark/DefaultSource.java
- src/main/java/com/marklogic/spark/reader/ReadContext.java
And ensuring an error occurs if the serverTimestamp is not set. That scenario cannot be tested and there's no way to force it to happen, it's more to guard against a bug in the future.
> DEVEXP-390 Only inferring schema if necessary

- caddy/config/Caddyfile
- docker-compose.yaml
- docs/configuration.md
- src/main/java/com/marklogic/spark/Options.java
- src/main/java/com/marklogic/spark/writer/DocBuilder.java
- src/main/java/com/marklogic/spark/writer/DocBuilderFactory.java
- src/main/java/com/marklogic/spark/writer/MarkLogicDataWriter.java
- src/main/java/com/marklogic/spark/writer/WriteContext.java
- src/test/java/com/marklogic/spark/AbstractIntegrationTest.java
- src/test/java/com/marklogic/spark/writer/AbstractWriteTest.java
- src/test/java/com/marklogic/spark/writer/WriteRowsTest.java
- src/test/java/com/marklogic/spark/writer/WriteRowsWithTransformTest.java
- src/test/ml-config/temporal/axes/temporal-system-axis.json
- src/test/ml-config/temporal/axes/temporal-valid-axis.json
- src/test/ml-config/temporal/collections/temporal-collection.json
- src/test/ml-data/collections.properties
- src/test/ml-modules/transforms/transformToXml.xqy
- src/test/ml-modules/transforms/withParams.sjs
- src/test/resources/temporal-data.csv
Had to add temporal config to the test app so we can test temporal stuff, so that added several new files. 
Also modified the docker-compose stuff so that 8015 can be used during mlDeploy in order to deploy the REST transforms.
> DEVEXP-436 Can now configure document props

- docs/getting-started-pyspark.md
- docs/reading.md
- src/main/java/com/marklogic/spark/ContextSupport.java
- src/main/java/com/marklogic/spark/MarkLogicTable.java
- src/main/java/com/marklogic/spark/reader/MarkLogicMicroBatchStream.java
- src/main/java/com/marklogic/spark/reader/MarkLogicScan.java
- src/main/java/com/marklogic/spark/reader/PlanAnalysis.java
- src/main/java/com/marklogic/spark/reader/ReadContext.java
- src/test/java/com/marklogic/spark/AbstractIntegrationTest.java
- src/test/java/com/marklogic/spark/reader/ReadStreamOfRowsTest.java
- src/test/java/com/marklogic/spark/reader/ReadWithClientUriTest.java
- src/test/java/com/marklogic/spark/writer/AbstractWriteTest.java
- src/test/java/com/marklogic/spark/writer/StreamRowsTest.java
- src/test/java/com/marklogic/spark/writer/WriteRowsTest.java
Most of the new stuff is in the new `MarkLogicMicroBatchStream` class, which uses a bucket index as an offset.
> DEVEXP-451 Can now use readStream

- docs/reading.md
- src/main/java/com/marklogic/spark/reader/MarkLogicScanBuilder.java
- src/main/java/com/marklogic/spark/reader/ReadContext.java
- src/test/java/com/marklogic/spark/reader/AbstractPushDownTest.java
- src/test/java/com/marklogic/spark/reader/PushDownFilterTest.java
- src/test/java/com/marklogic/spark/reader/PushDownOffsetTest.java
- src/test/java/com/marklogic/spark/reader/PushDownOrderByAndLimitTest.java
Realized that orderBy needs to be done with limit per Spark's `SupportsPushDownTopN` interface. 
All 3 are implemented simply by adding the appropriate operator to the user's serialized Optic plan.
> DEVEXP-462 Now pushing down orderBy, limit, and offset

- build.gradle
- src/main/java/com/marklogic/spark/DefaultSource.java
- src/main/java/com/marklogic/spark/MarkLogicTable.java
- src/test/java/com/marklogic/spark/reader/ReadRowsWithBasicAuthTest.java
Issue was that the case-insensitive map was used for inferring a schema, which meant that "authType" became "authtype" and was thus ignored by the Java Client.
> authType can now be overridden

- src/main/java/com/marklogic/spark/reader/MarkLogicScanBuilder.java
- src/main/java/com/marklogic/spark/reader/PlanAnalysis.java
- src/main/java/com/marklogic/spark/reader/ReadContext.java
- src/test/java/com/marklogic/spark/reader/PushDownCountTest.java
- src/test/java/com/marklogic/spark/reader/PushDownFilterTest.java
Had to rework the filter test to use "collectAsList" instead of "count" so that it could verify the number of rows returned by MarkLogic ("count()" will now always return 1).
> DEVEXP-467 Now pushing down count()

- docs/reading.md
- src/main/java/com/marklogic/spark/reader/MarkLogicScanBuilder.java
- src/main/java/com/marklogic/spark/reader/PlanUtil.java
- src/main/java/com/marklogic/spark/reader/ReadContext.java
- src/test/java/com/marklogic/spark/reader/PlanUtilTest.java
- src/test/java/com/marklogic/spark/reader/PushDownRequiredColumnsTest.java
Extracted `PlanUtil` as well so that all the plan manipulations happen in one place, and it's easier to unit test those.
> DEVEXP-468 Can now push down required columns

- src/main/java/com/marklogic/spark/reader/MarkLogicScanBuilder.java
- src/main/java/com/marklogic/spark/reader/PlanUtil.java
- src/main/java/com/marklogic/spark/reader/ReadContext.java
- src/test/java/com/marklogic/spark/reader/PushDownCountTest.java
Will optimize this later. This prevents an error from being thrown in the meantime.
> DEVEXP-467 Fix for count(); not pushing down when groupBy exists

- src/main/java/com/marklogic/spark/reader/MarkLogicPartitionReader.java
- src/main/java/com/marklogic/spark/reader/MarkLogicScanBuilder.java
- src/main/java/com/marklogic/spark/reader/PlanUtil.java
- src/main/java/com/marklogic/spark/reader/ReadContext.java
- src/test/java/com/marklogic/spark/reader/PushDownCountTest.java
- src/test/java/com/marklogic/spark/reader/PushDownGroupByCountTest.java
- src/test/java/com/marklogic/spark/reader/PushDownOrderByAndLimitTest.java
And... I implemented groupBy + count while I was in here fixing things as it was trivial to do. Also tweaked some logging based on testing. But the main thing is the addition of tests to verify that column names work, regardless of whether they have no qualifier, only a view, or a schema + view.
> Fixes for count/orderBy on qualified column names

- docs/index.md
- src/main/java/com/marklogic/spark/DefaultSource.java
All tests pass on 10.0-9, which introduced the `columnInfo` arg for /v1/rows.
The writer tests all pass in 9.0-9, which is the oldest version of MarkLogic available from hub.docker.
> Updated minimum versions

- build.gradle
- src/main/java/com/marklogic/spark/reader/ReadContext.java
Can't believe it, but resultDoc with JacksonHandle is consistently outperforming resultRows with a StringHandle. So not changing that code, just changed the comments.
> DEVEXP-477 Upgraded to Java Client 6.2.1

- src/main/java/com/marklogic/spark/reader/MarkLogicScanBuilder.java
- src/main/java/com/marklogic/spark/reader/ReadContext.java
- src/test/java/com/marklogic/spark/AbstractIntegrationTest.java
- src/test/java/com/marklogic/spark/reader/PushDownCountTest.java
- src/test/java/com/marklogic/spark/reader/PushDownFilterTest.java
- src/test/java/com/marklogic/spark/reader/PushDownGroupByCountTest.java
- src/test/java/com/marklogic/spark/reader/PushDownOffsetTest.java
- src/test/java/com/marklogic/spark/reader/PushDownRequiredColumnsTest.java
- src/test/java/com/marklogic/spark/reader/ReadRowsTest.java
- src/test/java/com/marklogic/spark/writer/WriteRowsTest.java
- src/test/ml-schemas/tde/no-authors.json
Need to do this in the ScanBuilder so we can return "false" to Spark to let it know that we did not push down the operation. 
Also added an assertion to WriteRowsTest to help debug what seems like an intermittent failure on Jenkins.
> Fix for not pushing down when count of rows is zero

- src/main/java/com/marklogic/spark/reader/SchemaInferrer.java
- src/test/java/com/marklogic/spark/reader/ReadRowsWithInferredSchemaTest.java
Also added "unknown" -> String since we're certain of that mapping now and it avoids several warning log messages.
> Ignoring allTypes test on MarkLogic 10

- src/main/java/com/marklogic/spark/reader/MarkLogicScanBuilder.java
Seeing logging about the pushdown operations seems helpful to ensure it's happening, and they're only logged once.
> Bumped up some debug logging to info

- src/main/java/com/marklogic/spark/reader/MarkLogicScanBuilder.java
- src/main/java/com/marklogic/spark/reader/PlanUtil.java
- src/main/java/com/marklogic/spark/reader/ReadContext.java
- src/test/java/com/marklogic/spark/reader/PushDownGroupByCountTest.java
Turns out this was a simple enhancement since `op.groupBy` already supports multiple column names being passed in.
> Improving groupBy pushdown to work for multiple column names

- docs/configuration.md
Figured it'd be worth at least touching on this. Because Spark options don't allow for objects to be passed in, it's not possible (or at least I don't know of a way) for a user to provide their own `X509TrustManager`. So using the JVM's default SSLContext seems like the way to go, which means the JVM's cacerts file needs to have the appropriate public certificate in it.
> Added docs section on configuring SSL

- build.gradle
- gradle/wrapper/gradle-wrapper.properties
Java Client 6.3 brings Jackson 2.15 along, which has multi-release classes in it. This caused shadow plugin 7.x to fail, but 8.x works fine. But using 8.x requires Gradle 8. So upgrading to latest Gradle 8.x. All looks fine so far.
> Fixing shadowJar task and bumped Java Client to 6.3

- src/main/java/com/marklogic/spark/writer/WriteContext.java
The logged warning was showing up even if the value for the URI prefix/suffix was null. No automated test included as we don't have a way to verify logging. So just did some quick manual testing.
> Quieting down some logging

- docs/Gemfile.lock
- docs/getting-started/pyspark.md
- docs/reading.md
- Added a TOC
- Moved all the Optic-specific sections under the overall "Reading via Optic" section
- Bumped "Error Handling" to the bottom since it'll be the same for both Optic and custom queries
There are some whitespace changes in terms of newline symbols, so be sure to ignore those when reviewing in GH.
> Added docs for reading via custom queries

- src/main/java/com/marklogic/spark/reader/CustomCodePartitionReader.java
- src/main/java/com/marklogic/spark/reader/JsonRowDeserializer.java
- src/main/java/com/marklogic/spark/reader/MarkLogicPartitionReader.java
- src/main/java/com/marklogic/spark/writer/DocBuilderFactory.java
- src/test/java/com/marklogic/spark/writer/WriteRowsTest.java
Had it duplicated in two places; hoping that the new `JsonRowDeserializer` also sheds light on the important task of converting a JSON string into a Spark row. 
Also addressed another TODO in DocBuilderFactory. 
All refactoring, no functional changes.
> DEVEXP-599 Refactored use of Spark's JacksonParser

- src/main/java/com/marklogic/spark/writer/MarkLogicWrite.java
Via some testing, I realized that with large numbers of partitions, logging all the commit messages isn't a great idea. So bumped that to debug, and made the abort messages at the "warn" level (as if the job was aborted, it was either intentional, or an error occurred which will already have copius logging).
> Tweaked logging in MarkLogicWrite

- src/main/java/com/marklogic/spark/MarkLogicTable.java
- src/main/java/com/marklogic/spark/reader/OpticBatch.java
- src/main/java/com/marklogic/spark/reader/OpticMicroBatchStream.java
- src/main/java/com/marklogic/spark/reader/OpticPartitionReader.java
- src/main/java/com/marklogic/spark/reader/OpticPartitionReaderFactory.java
- src/main/java/com/marklogic/spark/reader/OpticScan.java
- src/main/java/com/marklogic/spark/reader/OpticScanBuilder.java
- src/main/java/com/marklogic/spark/writer/MarkLogicWrite.java
- src/main/java/com/marklogic/spark/writer/SparkRowUriMaker.java
- src/main/java/com/marklogic/spark/writer/WriteBatcherDataWriter.java
- src/main/java/com/marklogic/spark/writer/WriteBatcherDataWriterFactory.java
- src/test/java/com/marklogic/spark/reader/AbstractPushDownTest.java
"MarkLogic" is still the prefix for Spark-required classes that aren't specific to using Optic or custom code.
> Rehnamed "MarkLogic" prefix to "Optic" prefix where appropriate

- docs/reading.md
- src/test/java/com/marklogic/spark/reader/ReadStreamWithCustomCodeTest.java
I realized this was a presumably-happy coincidence while testing - i.e. any user-defined variables for reading will also be sent to the code for obtaining batch IDs. There's no downside to this that I can identify - i.e. if some vars aren't used by a script, that's fine, no error is thrown.
> DEVEXP-619 Added docs and test for user variables for batch IDs code

- build.gradle
- examples/java-dependency/build.gradle
- examples/java-dependency/gradle/wrapper/gradle-wrapper.properties
- examples/java-dependency/src/main/java/org/example/App.java
Ran into an issue when testing the java-dependency project, where the Java Client's preferred Jackson version of 2.15.2 was being used, which Spark 3.4 does not like. Made me realize that we don't want our connector to bring any Jackson dependencies with it - it needs to use whatever the user's Spark distribution is using. So updated our build.gradle file to exclude the Jackson dependencies coming from java-client-api, ml-app-deployer, and marklogic-unit-test (the latter two ensure that we don't get any Jackson 2.15.2 dependencies when running the tests, but get Spark 3.4.1's preferred version instead, which is 2.14.2). 
After fixing this, I realized it's perfectly safe to use Java Client 6.4.0, as that was using Jackson 2.15.2 just like Java Client 6.3.0. So made that upgrade. All tests …
> Fixed issue with Jackson dependencies

- build.gradle
- docs/index.md
- src/test/java/com/marklogic/spark/reader/AbstractPushDownTest.java
- src/test/java/com/marklogic/spark/reader/DisablePushDownAggregatesTest.java
- src/test/java/com/marklogic/spark/reader/PushDownCountTest.java
- src/test/java/com/marklogic/spark/reader/PushDownFilterTest.java
- src/test/java/com/marklogic/spark/reader/PushDownGroupByAvgTest.java
- src/test/java/com/marklogic/spark/reader/PushDownGroupByCountTest.java
- src/test/java/com/marklogic/spark/reader/PushDownGroupByManyAggregatesTest.java
- src/test/java/com/marklogic/spark/reader/PushDownGroupByMaxTest.java
- src/test/java/com/marklogic/spark/reader/PushDownGroupByMeanTest.java
- src/test/java/com/marklogic/spark/reader/PushDownGroupByMinTest.java
- src/test/java/com/marklogic/spark/reader/PushDownGroupBySumTest.java
- src/test/java/com/marklogic/spark/reader/PushDownOrderByAndLimitTest.java
- src/test/java/com/marklogic/spark/reader/PushDownPivotTest.java
- src/test/java/com/marklogic/spark/reader/PushDownRequiredColumnsTest.java
And modified pushdown tests to not verify the number of rows read from MarkLogic when testing with Spark 3.5.0. The apparent change in Spark's pushdown support will be addressed in a future release. For now, this change to the tests provides an easy way to verify that the tests run correctly against Spark 3.3, 3.4, and 3.5.
> Added note about Spark version support

- src/test/java/com/marklogic/spark/AbstractIntegrationTest.java
- src/test/java/com/marklogic/spark/reader/ReadStreamOfRowsTest.java
- src/test/java/com/marklogic/spark/reader/customcode/ReadStreamWithCustomCodeTest.java
- src/test/java/com/marklogic/spark/writer/AbstractWriteTest.java
- src/test/java/com/marklogic/spark/writer/WriteStreamOfRowsTest.java
Just avoiding duplication of a long-ish string.
> Extracted constant for permissions

- Jenkinsfile
- src/main/java/com/marklogic/spark/MarkLogicTable.java
- src/main/java/com/marklogic/spark/reader/ReadContext.java
- src/test/java/com/marklogic/spark/SerializeUtil.java
- src/test/java/com/marklogic/spark/reader/SerializeOpticReaderObjectsTest.java
- src/test/java/com/marklogic/spark/reader/customcode/SerializeCustomCodeReaderTest.java
- src/test/java/com/marklogic/spark/writer/SerializeWriterObjectsTest.java
- src/test/java/com/marklogic/spark/writer/customcode/SerializeCustomCodeWriterTest.java
Turns out that they are serializable, but I wasn't certain as I thought no-arg constructors were required - but that doesn't appear to be the case based on what `SerializedUtil` does, and Spark does the same thing for its default serialization strategy. 
I made one impl change, though it has no functional impact - I modified ReadContext so that it's not trying to access an active SparkSession, which was making testing more difficult.
> Added tests to verify that serializable objects are serializable

- src/main/java/com/marklogic/spark/DefaultSource.java
- src/main/java/com/marklogic/spark/Options.java
- src/main/java/com/marklogic/spark/reader/document/DocumentBatch.java
- src/main/java/com/marklogic/spark/reader/document/DocumentContext.java
- src/main/java/com/marklogic/spark/reader/document/DocumentRowSchema.java
- src/main/java/com/marklogic/spark/reader/document/DocumentScan.java
- src/main/java/com/marklogic/spark/reader/document/DocumentScanBuilder.java
- src/main/java/com/marklogic/spark/reader/document/DocumentTable.java
- src/main/java/com/marklogic/spark/reader/document/ForestPartition.java
- src/main/java/com/marklogic/spark/reader/document/ForestReader.java
- src/main/java/com/marklogic/spark/reader/document/ForestReaderFactory.java
- src/main/java/com/marklogic/spark/reader/document/UriBatcher.java
- src/test/java/com/marklogic/spark/reader/document/ReadDocumentRowsTest.java
The critical part here is `UrisBatcher`. I'm going to do some scalability testing with that outside of this PR. 
Most everything else is just Spark-required boilerplate.
> Can now read document rows by collection

- src/main/java/com/marklogic/spark/DefaultSource.java
- src/main/java/com/marklogic/spark/MarkLogicFileTable.java
- src/main/java/com/marklogic/spark/MarkLogicTable.java
- src/main/java/com/marklogic/spark/reader/file/FileScanBuilder.java
- src/main/java/com/marklogic/spark/writer/file/DocumentFileBatch.java
- src/main/java/com/marklogic/spark/writer/file/DocumentFileWriteBuilder.java
- src/main/java/com/marklogic/spark/writer/file/DocumentFileWriter.java
- src/main/java/com/marklogic/spark/writer/file/DocumentFileWriterFactory.java
- src/test/java/com/marklogic/spark/writer/file/WriteDocumentFilesTest.java
Moved `MarkLogicFileTable` to base package so it can be reused for both reading and writing. 
`DocumentFileWriter` is the main code; the rest is Spark plumbing. It borrows chunks of code from MLCP for writing a file. 
We'll be updating the Factory here with additional writers very soon - e.g. a compressed file writer, an archive file writer, etc.
> Can now write documents as files

- src/main/java/com/marklogic/spark/Options.java
- src/main/java/com/marklogic/spark/reader/document/DocumentContext.java
- src/main/java/com/marklogic/spark/reader/document/DocumentRowSchema.java
- src/main/java/com/marklogic/spark/reader/document/ForestReader.java
- src/test/java/com/marklogic/spark/reader/document/ReadDocumentRowsWithMetadataTest.java
Most of this is just converting data in our `DocumentMetadataHandle` into the appropriate columns in a Spark row.
> MLE-11842 Can now read metadata columns when reading documents

- src/main/java/com/marklogic/spark/reader/document/DocumentTable.java
- src/main/java/com/marklogic/spark/writer/ArbitraryRowFunction.java
- src/main/java/com/marklogic/spark/writer/DocBuilder.java
- src/main/java/com/marklogic/spark/writer/DocumentRowFunction.java
- src/main/java/com/marklogic/spark/writer/FileRowFunction.java
- src/main/java/com/marklogic/spark/writer/WriteBatcherDataWriter.java
- src/test/java/com/marklogic/spark/AbstractIntegrationTest.java
- src/test/java/com/marklogic/spark/TestUtil.java
- src/test/java/com/marklogic/spark/reader/document/ReadDocumentRowsWithMetadataTest.java
- src/test/java/com/marklogic/spark/writer/document/WriteDocumentRowsToMarkLogicTest.java
Moved some things around too:
1. The logic in `WriteBatcherDataWriter` for building a document from a row is now spread across 3 classes, each responsible for a different type of row.
2. Created `TestUtil` for holding the logic for creating test documents with all types of metadata.
> MLE-11841 Can now write document rows to MarkLogic

- src/main/java/com/marklogic/spark/DefaultSource.java
- src/main/java/com/marklogic/spark/Options.java
- src/main/java/com/marklogic/spark/reader/document/DocumentContext.java
- src/main/java/com/marklogic/spark/reader/document/ForestReader.java
- src/main/java/com/marklogic/spark/reader/document/SearchQueryBuilder.java
- src/test/java/com/marklogic/spark/reader/document/ReadDocumentRowsTest.java
Turns out we don't need queryFormat - the REST API seems to figure out whether it's a JSON or XML query without having to configure it on the handle.
> MLE-11895 Can now use any of the 4 query types for reading documents

- .env
- docker-compose.yaml
This is for regression builds in Jenkins.
> Allowing for MarkLogic version to be overridden

- CONTRIBUTING.md
- src/main/java/com/marklogic/spark/DefaultSource.java
- src/main/java/com/marklogic/spark/Options.java
- src/main/java/com/marklogic/spark/reader/document/DocumentContext.java
- src/main/java/com/marklogic/spark/reader/document/ForestReader.java
- src/main/java/com/marklogic/spark/reader/document/SearchQueryBuilder.java
- src/main/java/com/marklogic/spark/writer/FileRowFunction.java
- src/test/java/com/marklogic/spark/reader/document/ReadDocumentRowsTest.java
- src/test/java/com/marklogic/spark/writer/WriteFileRowsTest.java
- src/test/java/com/marklogic/spark/writer/file/WriteDocumentZipFilesTest.java
Did a little renaming for consistency.
Added what should be very helpful logging in `ForestReader` for how much and how fast each forest is read.
Added example to CONTRIBUTING for common test case of querying for documents.
> Small enhancements from testing

- src/main/java/com/marklogic/spark/DefaultSource.java
- src/main/java/com/marklogic/spark/Options.java
- src/main/java/com/marklogic/spark/reader/document/DocumentContext.java
- src/main/java/com/marklogic/spark/reader/document/SearchQueryBuilder.java
- src/test/java/com/marklogic/spark/reader/document/ReadDocumentRowsTest.java
Realized a couple things:
1. User needs to be able to specify both a "string query" and a "complex query".
2. The query type doesn't matter, even though the Java Client seems to suggest that it does.
> Fixed design in reading documents

- src/main/java/com/marklogic/spark/reader/document/DocumentContext.java
- src/main/java/com/marklogic/spark/reader/document/ForestReader.java
- src/test/java/com/marklogic/spark/reader/document/ReadDocumentRowsTest.java
Made a nicer error for when batch size is invalid.
More importantly, changed how documents are retrieved to be done via a POST instead of a GET, thereby avoiding Request-URI length errors. Unfortunately was not able to create a test for this - was not able to generate the error locally.
> Couple fixes pertaining to batch size

- src/main/java/com/marklogic/spark/ContextSupport.java
- src/main/java/com/marklogic/spark/Options.java
- src/main/java/com/marklogic/spark/reader/document/DocumentBatch.java
- src/main/java/com/marklogic/spark/reader/document/DocumentContext.java
- src/main/java/com/marklogic/spark/reader/document/ForestPartition.java
- src/main/java/com/marklogic/spark/reader/document/ForestPartitionPlanner.java
- src/main/java/com/marklogic/spark/reader/document/ForestReader.java
- src/main/java/com/marklogic/spark/reader/document/SearchQueryBuilder.java
- src/main/java/com/marklogic/spark/reader/document/UriBatcher.java
- src/test/java/com/marklogic/spark/reader/document/MakeForestPartitionsTest.java
- src/test/java/com/marklogic/spark/reader/document/ReadDocumentRowsTest.java
- src/test/java/com/marklogic/spark/reader/document/ReadDocumentRowsWithPartitionCountsTest.java
- src/test/java/com/marklogic/spark/reader/optic/ReadRowsTest.java
- src/test/java/com/marklogic/spark/writer/WriteRowsTest.java
- src/test/java/com/marklogic/spark/writer/file/WriteDocumentZipFilesTest.java
The main guts here is in the new `ForestPartitionPlanner` along with changes to `UrisBatcher`. 
Interestingly, had to add "queryFormat" as a parameter in order to call `queryManager.search`, whereas `queryManager.uris` doesn't require it. 
Updated a few tests based on a slight tweak to how invalid number values are handled.
> MLE-12218 User can now configure partitions per forest

- docs/configuration.md
- docs/reading-data/documents.md
- src/main/java/com/marklogic/spark/Options.java
- src/main/java/com/marklogic/spark/reader/document/DocumentContext.java
- src/main/java/com/marklogic/spark/reader/document/SearchQueryBuilder.java
- src/test/java/com/marklogic/spark/reader/document/ReadDocumentRowsTest.java
Also changed default number of partitions per forest to 4 based on the default setup of 3 forests per host and 32 app server threads.
> Removed `queryFormat` and improved docs on performance

- build.gradle
- src/main/java/com/marklogic/spark/DefaultSource.java
- src/main/java/com/marklogic/spark/Options.java
- src/main/java/com/marklogic/spark/reader/document/DocumentRowSchema.java
- src/main/java/com/marklogic/spark/reader/file/FilePartitionReaderFactory.java
- src/main/java/com/marklogic/spark/reader/file/FileRowSchema.java
- src/main/java/com/marklogic/spark/reader/file/RdfFileReader.java
- src/main/java/com/marklogic/spark/reader/file/TripleRowSchema.java
- src/main/java/com/marklogic/spark/reader/file/TripleSerializer.java
- src/test/java/com/marklogic/spark/reader/file/ReadRdfFilesTest.java
- src/test/resources/rdf/blank-nodes.xml
- src/test/resources/rdf/mini-taxonomy.xml
Main things of note:
1. New `TripleRowSchema` instead of using document row schema, as we'll need to capture the graph for quads.
2. `TripleSerializer` is mostly copy/pasted (and cleaned up a bunch) from MLCP.
> MLE-12332 Can now read RDF/XML files

- src/main/java/com/marklogic/spark/reader/customcode/CustomCodeBatch.java
- src/main/java/com/marklogic/spark/reader/customcode/CustomCodeScan.java
- src/main/java/com/marklogic/spark/reader/document/DocumentBatch.java
- src/main/java/com/marklogic/spark/reader/document/DocumentScan.java
- src/main/java/com/marklogic/spark/reader/optic/OpticBatch.java
Was reading through the Spark javadocs as I saw the Batch objects being created multiple times and the partitions logic being called multiple times. That's not necessary for us - the partitions will be the same for each Batch object. So having the Scan object eagerly create a Batch when possible and having that Batch eagerly calculate its partitions as well. No functional change, but does make our logging less confusing because the user won't see what seem like duplicate log entries (like for the number of partitions being used for reading documents).
> Small tweaks to avoid unnecessary object creation

- src/main/java/com/marklogic/spark/reader/file/MlcpMetadataConverter.java
- src/test/java/com/marklogic/spark/reader/file/ConvertMlcpMetadataTest.java
- src/test/resources/mlcp-metadata/complete.xml
This is intended to be used by MLE-12388 - importing an MLCP archive. The intent is that an MLCP metadata document can be converted by `MlcpMetadataConverter` into a `DocumentMetadataHandle` object, which can then be converted into the appropriate column values in our `DocumentRowSchema`.
> MLE-12717 Can now convert MLCP metadata into REST metadata

- src/main/java/com/marklogic/spark/writer/CommitMessage.java
- src/main/java/com/marklogic/spark/writer/MarkLogicWrite.java
- src/main/java/com/marklogic/spark/writer/WriteBatcherDataWriter.java
- src/main/java/com/marklogic/spark/writer/WriteBatcherDataWriterFactory.java
- src/main/java/com/marklogic/spark/writer/customcode/CustomCodeWriter.java
- src/main/java/com/marklogic/spark/writer/customcode/CustomCodeWriterFactory.java
- src/main/java/com/marklogic/spark/writer/file/ContentWriter.java
- src/main/java/com/marklogic/spark/writer/file/DocumentFileBatch.java
- src/main/java/com/marklogic/spark/writer/file/DocumentFileWriter.java
- src/main/java/com/marklogic/spark/writer/file/FileCommitMessage.java
- src/main/java/com/marklogic/spark/writer/file/ZipCommitMessage.java
- src/main/java/com/marklogic/spark/writer/file/ZipFileWriter.java
I revamped our commit messages, as I realized now that we log useful summary metrics, there's little to no value in debug logging of the messages themselves:
- Removed partitionId / taskId / epochId from the messages (these were being logged at the debug level, but I don't see any value in that).
- Added new commit message objects for files and zips.
> MLE-12373 Added logging for file metrics

- src/main/java/com/marklogic/spark/reader/file/AbstractRdfFileReader.java
- src/main/java/com/marklogic/spark/reader/file/AggregateXMLFileReader.java
- src/main/java/com/marklogic/spark/reader/file/FileBatch.java
- src/main/java/com/marklogic/spark/reader/file/FileContext.java
- src/main/java/com/marklogic/spark/reader/file/FilePartition.java
- src/main/java/com/marklogic/spark/reader/file/FilePartitionReaderFactory.java
- src/main/java/com/marklogic/spark/reader/file/GZIPAggregateXMLFileReader.java
- src/main/java/com/marklogic/spark/reader/file/GZIPFileReader.java
- src/main/java/com/marklogic/spark/reader/file/MlcpArchiveFileReader.java
- src/main/java/com/marklogic/spark/reader/file/QuadsFileReader.java
- src/main/java/com/marklogic/spark/reader/file/RdfZipFileReader.java
- src/main/java/com/marklogic/spark/reader/file/TriplesFileReader.java
- src/main/java/com/marklogic/spark/reader/file/ZipAggregateXMLFileReader.java
- src/main/java/com/marklogic/spark/reader/file/ZipFileReader.java
- src/test/java/com/marklogic/spark/reader/file/ReadGZIPAggregateXMLFilesTest.java
No functional change here. Adding `FileContext` for the following reasons:
1. Can carry out the map of properties and the SerializableConfiguration class.
2. Can have convenience methods for parsing options.
3. Can have a very useful `open` method that is used by every file reader. 
4. Will add `isReadAbortOnFailure()` to it in the next PR.
> MLE-12523 Refactor: Adding FileContext

- src/main/java/com/marklogic/spark/reader/file/AggregateXmlFileReader.java
- src/main/java/com/marklogic/spark/reader/file/AggregateXmlSplitter.java
- src/main/java/com/marklogic/spark/reader/file/FilePartitionReaderFactory.java
- src/main/java/com/marklogic/spark/reader/file/GzipFileReader.java
- src/main/java/com/marklogic/spark/reader/file/ZipAggregateXmlFileReader.java
- src/main/java/com/marklogic/spark/writer/file/DocumentFileWriterFactory.java
- src/main/java/com/marklogic/spark/writer/file/GzipFileWriter.java
- src/test/java/com/marklogic/spark/reader/file/ReadAggregateXmlFilesTest.java
- src/test/java/com/marklogic/spark/reader/file/ReadAggregateXmlZipFilesTest.java
- src/test/java/com/marklogic/spark/reader/file/ReadGzipAggregateXmlFilesTest.java
- src/test/java/com/marklogic/spark/reader/file/ReadGzipFilesTest.java
- src/test/java/com/marklogic/spark/writer/file/WriteDocumentGzipFilesTest.java
We were mostly doing lower-camel-case, but not everywhere. No functional changes here, just renames.
> Refactor: Standardize on lower-camel-case for acronyms

- docs/configuration.md
- docs/writing.md
- src/main/java/com/marklogic/spark/Options.java
- src/main/java/com/marklogic/spark/writer/ArbitraryRowConverter.java
- src/main/java/com/marklogic/spark/writer/SparkRowUriMaker.java
- src/test/java/com/marklogic/spark/writer/WriteFileRowsTest.java
- src/test/java/com/marklogic/spark/writer/WriteRowsWithJsonRootNameTest.java
- src/test/java/com/marklogic/spark/writer/WriteRowsWithUriTemplateTest.java
I stumbled into an enhancement while writing the test - uriTemplate expressions now support JSONPointer, which is indicated by an expression starting with "/". That allowed my test to work.
> MLE-12813 Can now set a root JSON name

- src/main/java/com/marklogic/spark/reader/file/AggregateXmlSplitter.java
- src/test/java/com/marklogic/spark/writer/WriteSparkJsonTest.java
- src/test/resources/spark-json/array-of-objects.json
- src/test/resources/spark-json/json-lines.txt
- src/test/resources/spark-json/single-object.json
This shows how Spark JSON can be used for the common use case of reading each object in an array in a JSON file as a separate row, and then writing each row to MarkLogic as a separate document. So we don't need our own file reader for this. 
I retained some naming improvements in `AggregateXmlSplitter`, but those are non-functional changes.
> MLE-12822 Added tests for Spark JSON

- src/main/java/com/marklogic/spark/reader/document/DocumentRowSchema.java
- src/main/java/com/marklogic/spark/reader/document/ForestReader.java
- src/main/java/com/marklogic/spark/reader/file/MlcpMetadata.java
- src/main/java/com/marklogic/spark/reader/file/MlcpMetadataConverter.java
- src/test/java/com/marklogic/spark/reader/file/ConvertMlcpMetadataTest.java
This does 2 things:
1. Moves a bunch of logic into DocumentRowSchema so it can be reused by MlcpArchiveFileReader.
2. Enhances MlcpMetadataConverter to handle the MLCP format value. (Technically not a refactor, but it's a tiny change).
> MLE-12390 Refactoring in preparation for real PR

- src/main/java/com/marklogic/spark/reader/document/DocumentRowBuilder.java
- src/main/java/com/marklogic/spark/reader/document/DocumentRowSchema.java
- src/main/java/com/marklogic/spark/reader/document/ForestReader.java
- src/main/java/com/marklogic/spark/reader/file/ArchiveFileReader.java
- src/main/java/com/marklogic/spark/reader/file/MlcpArchiveFileReader.java
- src/test/java/com/marklogic/spark/reader/file/ReadArchiveFileTest.java
Started to duplicate this again for 12850 and decided to refactor via the new `DocumentRowBuilder` class. 
Also fixed one bug - the "format" column should not be XML when reading from an archive zip; we don't know what the format is because there's no indication in the zip. 
It is possible to populate "format" for MLCP archives because the MLCP metadata does contain a "format" element.
> MLE-12850 Refactor of code for builing document rows

- src/main/java/com/marklogic/spark/Options.java
- src/main/java/com/marklogic/spark/writer/BatchRetrier.java
- src/main/java/com/marklogic/spark/writer/MarkLogicWrite.java
- src/main/java/com/marklogic/spark/writer/WriteBatcherDataWriter.java
- src/main/java/com/marklogic/spark/writer/WriteBatcherDataWriterFactory.java
- src/main/java/com/marklogic/spark/writer/file/ZipFileWriter.java
- src/test/java/com/marklogic/spark/writer/SerializeWriterObjectsTest.java
- src/test/java/com/marklogic/spark/writer/WriteArchiveOfFailedDocumentsTest.java
I'm going to do a lot of manual testing with this, but it all seems straightforward - just create a `ZipFileWriter` and convert each failed `DocumentWriteOperation` into a row that the archive writer can add to a zip file as two separate entries.
> MLE-12850 Can now write archive of failed documents

- src/main/java/com/marklogic/spark/ContextSupport.java
- src/main/java/com/marklogic/spark/DefaultSource.java
- src/main/java/com/marklogic/spark/reader/customcode/CustomCodeContext.java
- src/main/java/com/marklogic/spark/reader/document/SearchQueryBuilder.java
- src/main/java/com/marklogic/spark/reader/optic/ReadContext.java
- src/main/java/com/marklogic/spark/reader/optic/SchemaInferrer.java
- src/main/java/com/marklogic/spark/writer/FileRowConverter.java
- src/main/java/com/marklogic/spark/writer/SparkRowUriMaker.java
- src/main/java/com/marklogic/spark/writer/WriteContext.java
- src/main/java/com/marklogic/spark/writer/rdf/RdfRowConverter.java
- src/main/resources/marklogic-spark-messages.properties
- src/test/java/com/marklogic/spark/reader/document/BuildSearchQueryTest.java
- src/test/java/com/marklogic/spark/reader/document/ReadDocumentRowsTest.java
- src/test/java/com/marklogic/spark/reader/document/ReadDocumentRowsWithPartitionCountsTest.java
- src/test/java/com/marklogic/spark/reader/optic/ReadRowsTest.java
- src/test/java/com/marklogic/spark/reader/optic/ReadStreamOfRowsTest.java
- src/test/java/com/marklogic/spark/reader/optic/ReadWithClientUriTest.java
- src/test/java/com/marklogic/spark/writer/WriteFileRowsTest.java
- src/test/java/com/marklogic/spark/writer/WriteRowsTest.java
- src/test/java/com/marklogic/spark/writer/WriteRowsWithTransformTest.java
- src/test/java/com/marklogic/spark/writer/WriteRowsWithUriTemplateTest.java
Will have a follow up PR in spark-etl to override each of these option names with a CLI option. 
Did some cleanup of error messages as well while I was at it, as well as throwing `ConnectorException` more consistently. So a lot of little changes, nothing major though.
> MLE-12333 Option names in error messages can now be overridden

- src/main/java/com/marklogic/spark/reader/optic/PlanUtil.java
- src/main/java/com/marklogic/spark/reader/optic/ReadContext.java
- src/test/java/com/marklogic/spark/reader/optic/PushDownFilterTest.java
Was able to reproduce the bug by including 2 filters, one of which produced a `sqlCondition`. I was not able to reproduce an issue where an `and` is created with a `sqlCondition` on the left or right. Have not figured out a way to force Spark to pass that to our connector.
> MLE-13771 Fixing bug where sqlCondition was added to op.and

- src/main/java/com/marklogic/spark/MarkLogicTable.java
- src/main/java/com/marklogic/spark/reader/optic/OpticBatch.java
- src/main/java/com/marklogic/spark/reader/optic/OpticMicroBatchStream.java
- src/main/java/com/marklogic/spark/reader/optic/OpticPartitionReader.java
- src/main/java/com/marklogic/spark/reader/optic/OpticPartitionReaderFactory.java
- src/main/java/com/marklogic/spark/reader/optic/OpticReadContext.java
- src/main/java/com/marklogic/spark/reader/optic/OpticScan.java
- src/main/java/com/marklogic/spark/reader/optic/OpticScanBuilder.java
- src/test/java/com/marklogic/spark/reader/optic/SerializeOpticReaderObjectsTest.java
Pure refactor - no functional changes. Wanted to make it more clear that this class is associated with an Optic query and not just any old read operation.
> Renamed `ReadContext` to `OpticReadContext`

- src/main/java/com/marklogic/spark/writer/BatchRetrier.java
- src/main/java/com/marklogic/spark/writer/WriteBatcherDataWriter.java
- src/test/java/com/marklogic/spark/writer/WriteArchiveOfFailedDocumentsTest.java
The `BatchRetrier` was neglecting to bump up the success item count when a batch succeeded.
> Fixed bug where success item count wasn't incremented

- build.gradle
Realized that since we're publishing the shadow jar for the connector - i.e. the jar that contains all of the dependencies, including several whose packages are relocated to avoid conflicts with Spark - that we don't want any dependencies declared since a user gets all of them via the single connector jar. 
Did a little Gradle trickery to accomplish this - made a new `shadowDependencies` configuration that acts like `implementation` but avoids adding any dependencies to the pom.xml file. 
Also fixed an issue where Jackson dependencies from Jena could take precedence over what Spark requires.
> Removing published dependencies

- src/test/java/com/marklogic/spark/reader/optic/ReadRowsFromTempViewTest.java
Intended to provide at least some verification that our connector works properly in conjunction with a Spark temp view.
> Added JUnit test for Spark temp views

- src/main/java/com/marklogic/spark/reader/file/FilePartitionReaderFactory.java
- src/main/java/com/marklogic/spark/reader/file/FileUtil.java
- src/main/java/com/marklogic/spark/reader/file/GenericFileReader.java
- src/test/java/com/marklogic/spark/reader/file/ReadGenericFilesTest.java
- src/test/java/com/marklogic/spark/writer/WriteArchiveOfFailedDocumentsTest.java
- src/test/java/com/marklogic/spark/writer/WritePartialBatchTest.java
Switched a couple tests over to use our connector for reading generic files. We still need tests for binaryFile as we support writing rows conforming to the schema used by binaryFile.
> MLE-14385 Can now read generic files

- src/test/java/com/marklogic/spark/reader/optic/ReadRowsFromTempViewTest.java
This is failing with the 2.2.0 connector but was likely fixed as part of MLE-13787.
> Added test for 'locate' in a SQL query

- src/main/java/com/marklogic/spark/DefaultSource.java
- src/main/java/com/marklogic/spark/reader/optic/OpticBatch.java
- src/main/java/com/marklogic/spark/reader/optic/OpticReadContext.java
- src/main/java/com/marklogic/spark/reader/optic/OpticScan.java
- src/main/java/com/marklogic/spark/reader/optic/OpticScanBuilder.java
- src/main/java/com/marklogic/spark/reader/optic/PlanUtil.java
- src/test/java/com/marklogic/spark/reader/optic/GroupByDuplicateColumnNamesTest.java
Tweaked some debug/trace logging as well while testing this. 
Note the second test case - we're not able to support `withColumn` when it simply aliases another column.
> MLE-14413 Fixing bug with duplicate groupBy column names

- src/main/java/com/marklogic/spark/Options.java
- src/main/java/com/marklogic/spark/writer/DocumentRowConverter.java
- src/main/java/com/marklogic/spark/writer/FileRowConverter.java
- src/main/java/com/marklogic/spark/writer/WriteBatcherDataWriter.java
- src/main/java/com/marklogic/spark/writer/WriteContext.java
- src/main/resources/marklogic-spark-messages.properties
- src/test/java/com/marklogic/spark/writer/document/WriteDocumentRowsToMarkLogicTest.java
Deprecated the "fileRows" option, as "documentType" is now useful any time we're writing document rows and the user wants to force a document type when MarkLogic cannot determine one.
> MLE-14384 User can now force document type

- src/main/java/com/marklogic/spark/ContextSupport.java
- src/main/java/com/marklogic/spark/Options.java
- src/main/java/com/marklogic/spark/writer/MarkLogicWrite.java
- src/main/java/com/marklogic/spark/writer/WriteContext.java
- src/main/resources/marklogic-spark-messages.properties
- src/test/java/com/marklogic/spark/writer/WriteRowsTest.java
We may not stick with this name. In hindsight, it would be better if `threadCount` referred to this number so a user didn't need to think about partitions, and we could have `partitionThreadCount` as well.
> MLE-14516 User can now configure total thread count

- src/main/java/com/marklogic/spark/writer/ArbitraryRowConverter.java
- src/test/java/com/marklogic/spark/writer/WriteRowsWithFilePathTest.java
This may not be used by a connector user, but it'll be used by Flux when importing files via a Spark data source.
> Adding support for using the Spark file path for a URI

- src/main/java/com/marklogic/spark/ContextSupport.java
- src/main/java/com/marklogic/spark/Options.java
- src/main/java/com/marklogic/spark/writer/WriteContext.java
- src/main/java/com/marklogic/spark/writer/customcode/CustomCodeWriter.java
- src/test/java/com/marklogic/spark/writer/WriteRowsTest.java
- src/test/java/com/marklogic/spark/writer/customcode/ProcessWithCustomCodeTest.java
Works for writing documents (the main use case) and reprocessing data (also a good use case). Not doing anything for exporting yet because in most cases in Flux, we don't have control over the data source used for writing.
> Added logging of progress

- build.gradle
- src/main/java/com/marklogic/spark/reader/JsonRowDeserializer.java
No longer needed as we only support Java 11 or higher. This was a shim only needed for Java 8 support.
> Removed scala-java8-compat

- src/main/java/com/marklogic/spark/writer/file/FileUtil.java
- src/test/java/com/marklogic/spark/writer/file/FileUtilTest.java
- src/test/java/com/marklogic/spark/writer/file/WriteDocumentFilesTest.java
Was previously throwing an error, but MLCP just logs the error and uses the URI as the file path. We're now doing the same thing.
> Fixing issue with URIs that cannot be parsed

- build.gradle
- src/main/java/com/marklogic/spark/JsonRowSerializer.java
- src/main/java/com/marklogic/spark/Options.java
- src/main/java/com/marklogic/spark/Util.java
- src/main/java/com/marklogic/spark/reader/JsonRowDeserializer.java
- src/main/java/com/marklogic/spark/writer/ArbitraryRowConverter.java
- src/main/java/com/marklogic/spark/writer/customcode/CustomCodeWriter.java
- src/test/java/com/marklogic/spark/writer/WriteNullValuesTest.java
- src/test/resources/csv-files/empty-values.csv
- src/test/resources/json-lines/nested-objects.txt
Had to make a few changes:
1. Extracted the code for generating a Spark `JSONOptions` object along with the duplicated code for serializing a Spark row into JSON - that's all now in `JsonRowSerializer`. 
2. User can now specify `spark.marklogic.write.json.(name of option)=value` to include any option defined in Spark's `JSONOptions` class. The main one of interest is "ignoreNullFields". We'll include support for that in Flux via a new `--include-null-fields` option for some import commands (definitely for CSV). 
3. Reworked `ArbitraryRowConverter` to now happily use Jackson XML instead of the JSON library for converting JSON into an XML string.
> Can now include null fields

- src/main/java/com/marklogic/spark/JsonRowSerializer.java
- src/test/java/com/marklogic/spark/writer/IgnoreNullValuesTest.java
- src/test/java/com/marklogic/spark/writer/WriteRowsWithFilePathTest.java
- src/test/java/com/marklogic/spark/writer/WriteSparkJsonTest.java
This matches MLCP behavior for delimited files. And null fields are easy to query on and thus useful. And a user can easily drop them as well if desired.
> Defaulting to including null fields.

- CONTRIBUTING.md
- src/main/java/com/marklogic/spark/DefaultSource.java
- src/main/java/com/marklogic/spark/Options.java
- src/main/java/com/marklogic/spark/ProgressLogger.java
- src/main/java/com/marklogic/spark/WriteProgressLogger.java
- src/main/java/com/marklogic/spark/writer/WriteContext.java
- src/main/java/com/marklogic/spark/writer/customcode/CustomCodeWriter.java
- src/test/java/com/marklogic/spark/writer/WriteRowsTest.java
Realized in a Spark environment, the static for counting written docs wasn't getting reset. Did some refactoring to avoid duplicated code as well, and also to setup for potentially logging progress on reads.
Also defaulting the progress interval to 0 instead of 10000. This doesn't seem as useful in a Spark environment. Flux will default it to 10000 instead.
> Fixed progress logging bug

- src/main/java/com/marklogic/spark/DefaultSource.java
- src/main/java/com/marklogic/spark/Options.java
- src/main/java/com/marklogic/spark/ReadProgressLogger.java
- src/main/java/com/marklogic/spark/WriteProgressLogger.java
- src/main/java/com/marklogic/spark/reader/document/ForestReader.java
- src/main/java/com/marklogic/spark/reader/document/OpticTriplesReader.java
- src/main/java/com/marklogic/spark/reader/optic/OpticPartitionReader.java
- src/main/java/com/marklogic/spark/reader/optic/OpticReadContext.java
- src/test/java/com/marklogic/spark/reader/document/ReadDocumentRowsTest.java
- src/test/java/com/marklogic/spark/reader/triples/ReadTriplesTest.java
Had to make two separate loggers so we can have a static counter for reading and a static counter for writing. Both get reset when DefaultSource is created. 
Did some quick manual testing of this in Flux, and it "just works". 
Note that progress for reading/writing files is not being addressed yet. Just focusing on progress for reading from MarkLogic and writing to MarkLogic.
> Now logging progress for read operations

- CONTRIBUTING.md
- examples/entity-aggregation/build.gradle
- examples/java-dependency/build.gradle
- gradle.properties
3.4.3 is the latest 3.4.x release and is "strongly recommended" by the Spark team. This change does not impact our connector though, as we don't include any Spark libraries in our connector. It's just ensuring we compile and test against the latest 3.4.x release.
> Testing against Spark 3.4.3

- src/main/java/com/marklogic/spark/writer/WriteBatcherDataWriter.java
- src/main/java/com/marklogic/spark/writer/customcode/CustomCodeWriter.java
"stopping the job" wasn't accurate, as it's only one writer and there could be many other writers still active.
> Clarified a few log messages

- build.gradle
Not expecting any issues, as the 7.0-SNAPSHOT was basically the same as the now-final 7.0.0.
> Bumping to Java Client 7.0

- src/main/java/com/marklogic/spark/MarkLogicFileTable.java
- src/main/java/com/marklogic/spark/Options.java
- src/main/java/com/marklogic/spark/reader/file/GenericFileReader.java
- src/main/java/com/marklogic/spark/writer/DocumentRowConverter.java
- src/test/java/com/marklogic/spark/reader/file/ReadGenericFilesStreamingTest.java
Fairly simple fix - the file is no longer read during the reader phase but rather during the writer phase to avoid reading it entirely into memory.
> MLE-17041 Can now stream when reading generic files

- src/main/java/com/marklogic/spark/ContextSupport.java
- src/main/java/com/marklogic/spark/Options.java
- src/main/java/com/marklogic/spark/reader/document/DocumentContext.java
- src/main/java/com/marklogic/spark/reader/document/DocumentScanBuilder.java
- src/main/java/com/marklogic/spark/writer/file/ContentWriter.java
- src/test/java/com/marklogic/spark/writer/file/PrettyPrintFilesTest.java
- src/test/java/com/marklogic/spark/writer/file/WriteDocumentFilesTest.java
Similar approach to importing - defer reading docs from MarkLogic until the writer phase.
> MLE-17041 Can now stream when writing generic files

- src/main/java/com/marklogic/spark/reader/document/DocumentContext.java
- src/main/java/com/marklogic/spark/reader/document/ForestReader.java
- src/main/java/com/marklogic/spark/reader/document/UrisPage.java
The `documentManager.search` call was still retrieving the content, though it was ignored. That call is now never made when streaming documents to files. No tests, as verifying that this works would require a very large (many gb) file.
> Optimized streaming read

- docs/reading-data/reading-files/generic-file-support.md
We have a lot of gaps in our connector docs as the focus has been on Flux, but this gets at least some mention of streaming into the connector docs.
> Added docs for streaming files

- src/main/java/com/marklogic/spark/reader/file/ArchiveFileReader.java
- src/main/java/com/marklogic/spark/reader/file/FileContext.java
- src/main/java/com/marklogic/spark/reader/file/GenericFileReader.java
- src/main/java/com/marklogic/spark/reader/file/GzipFileReader.java
- src/main/java/com/marklogic/spark/reader/file/MlcpArchiveFileReader.java
- src/main/java/com/marklogic/spark/reader/file/RdfFileReader.java
- src/main/java/com/marklogic/spark/reader/file/RdfZipFileReader.java
- src/main/java/com/marklogic/spark/reader/file/ZipFileReader.java
- src/main/java/com/marklogic/spark/reader/file/xml/AggregateXmlFileReader.java
- src/main/java/com/marklogic/spark/reader/file/xml/ZipAggregateXmlFileReader.java
- src/main/java/com/marklogic/spark/writer/DocumentRowConverter.java
- src/test/java/com/marklogic/spark/reader/file/ReadGenericFilesStreamingTest.java
We can't encode the URI due to the PUT bug, but this at least fixes streaming so that it can read and write a file with spaces in its filename.
> MLE-17084 Fix for streaming files with spaces in filename

- src/main/java/com/marklogic/spark/reader/file/ArchiveFileReader.java
- src/main/java/com/marklogic/spark/writer/file/ZipFileWriter.java
- src/test/java/com/marklogic/spark/writer/file/WriteArchiveTest.java
This is a non-breaking change, as the reader will determine based on the first entry name whether it's the "legacy" or the new format.
> MLE-17059 Changing order of entries in archive

- src/main/java/com/marklogic/spark/reader/file/ArchiveFileReader.java
- src/main/java/com/marklogic/spark/writer/ArbitraryRowConverter.java
- src/main/java/com/marklogic/spark/writer/DocumentRowConverter.java
- src/main/java/com/marklogic/spark/writer/FileRowConverter.java
- src/main/java/com/marklogic/spark/writer/RowConverter.java
- src/main/java/com/marklogic/spark/writer/WriteBatcherDataWriter.java
- src/main/java/com/marklogic/spark/writer/rdf/RdfRowConverter.java
This allows for the archive streaming feature to return more than one document per Spark row. Has no effect on existing behavior. 
No longer need the `Content` class, so removed that. 
Also did some refactoring in `ArchiveFileReader` to shorten methods and make it more readable.
> MLE-17095 Refactoring; changed row converter to return iterator

- src/main/java/com/marklogic/spark/Util.java
- src/main/java/com/marklogic/spark/reader/document/DocumentContext.java
- src/main/java/com/marklogic/spark/reader/document/DocumentScanBuilder.java
- src/main/java/com/marklogic/spark/reader/document/ForestReader.java
- src/main/java/com/marklogic/spark/reader/file/GenericFileReader.java
- src/main/java/com/marklogic/spark/writer/file/ContentWriter.java
- src/main/java/com/marklogic/spark/writer/file/ZipFileWriter.java
- src/test/java/com/marklogic/spark/writer/file/WriteArchiveTest.java
Was fairly simple, since `ContentWriter` already supported streaming normal documents.
> MLE-17095 Can now stream when exporting an archive

- src/main/java/com/marklogic/spark/reader/file/ArchiveFileReader.java
- src/main/java/com/marklogic/spark/reader/file/FileContext.java
- src/main/java/com/marklogic/spark/reader/file/FileUtil.java
- src/main/java/com/marklogic/spark/reader/file/GenericFileReader.java
- src/main/java/com/marklogic/spark/reader/file/StreamingMode.java
- src/main/java/com/marklogic/spark/reader/file/ZipFileReader.java
- src/main/java/com/marklogic/spark/writer/DocumentRowConverter.java
- src/main/java/com/marklogic/spark/writer/file/ArchiveFileIterator.java
- src/main/java/com/marklogic/spark/writer/file/ZipFileIterator.java
- src/test/java/com/marklogic/spark/reader/file/ReadZipFilesTest.java
Going to do export next - which may "just work", will add a test first. 
This is similar to archive streaming where it may ultimately be better to make a separate file reader. It's a tradeoff of duplicating some logic into separate readers vs having more conditionals in one reader.
> MLE-17141 Can now stream normal zip files into MarkLogic

- CONTRIBUTING.md
- Jenkinsfile
- build.gradle
- docker-compose.yaml
- src/main/java/com/marklogic/spark/reader/file/ZipFileReader.java
My local Sonar on 10.2-1 crapped out locally. Couldn't revive it. But then found that the latest sonarqube - 10.6 - is running just fine, though it requires Java 17.
Bumped up some test dependencies and removed the "signing" plugin which is no longer needed. 
Also removed the dependency check plug-in, as we're not making use of it yet.
> Updated Sonar to latest version

- CONTRIBUTING.md
- src/main/java/com/marklogic/spark/writer/DocumentRowConverter.java
- src/main/java/com/marklogic/spark/writer/WriteBatcherDataWriter.java
- src/main/java/com/marklogic/spark/writer/file/ArchiveFileIterator.java
- src/main/java/com/marklogic/spark/writer/file/FileIterator.java
- src/main/java/com/marklogic/spark/writer/file/GzipFileIterator.java
- src/main/java/com/marklogic/spark/writer/file/ZipFileIterator.java
- src/test/java/com/marklogic/spark/reader/file/ReadGzipFilesTest.java
- src/test/java/com/marklogic/spark/reader/file/StreamGenericFilesTest.java
- src/test/java/com/marklogic/spark/reader/file/StreamGzipFilesTest.java
Sonar flagged the fact that the GZip streaming support was resulting in an unclosed stream. Reworked the internal API a bit so that each iterator can now be Closeable as well.
> MLE-17142 Ensuring input streams are closed

- build.gradle
- gradle.properties
3.5.3 is working well with Flux too.
> Bumping Spark compilation dependency to 3.5.3

- build.gradle
slf4j-api 1.7.x was sneaking in from the Java Client. The Java Client will be updated to use 2.x. But this ensures that all dependencies use slf4j-api 2.x, which avoids the logging issue referenced in the comment.
Also made a small optimization in shrinking the shadow jar size - we don't need any of the Jackson core dependencies for dataformat-xml, as Spark provides all of them.
> MLE-17232 Ensuring logging works in Flux

- src/main/java/com/marklogic/spark/ContextSupport.java
- src/main/java/com/marklogic/spark/Options.java
- src/main/java/com/marklogic/spark/reader/document/DocumentContext.java
- src/main/java/com/marklogic/spark/writer/DocumentProcessorFactory.java
- src/main/java/com/marklogic/spark/writer/WriteContext.java
- src/main/java/com/marklogic/spark/writer/customcode/CustomCodeWriter.java
- src/main/java/com/marklogic/spark/writer/splitter/ChunkConfig.java
- src/main/java/com/marklogic/spark/writer/splitter/DefaultChunkAssembler.java
- src/main/java/com/marklogic/spark/writer/splitter/DocumentSplitterFactory.java
- src/test/java/com/marklogic/spark/writer/splitter/SplitJsonDocumentTest.java
- src/test/java/com/marklogic/spark/writer/splitter/SplitterTest.java
Added ChunkConfig to pass all the chunk config around. Added getIntOption to avoid annoying casts to int. 
Going to support XML next, will then refactor a bit.
> MLE-17222 Supporting permissions, root name, and custom URI for chunks

- src/main/java/com/marklogic/spark/Options.java
- src/main/java/com/marklogic/spark/writer/DocumentProcessorFactory.java
- src/main/java/com/marklogic/spark/writer/splitter/ChunkConfig.java
- src/main/java/com/marklogic/spark/writer/splitter/DefaultChunkAssembler.java
- src/main/java/com/marklogic/spark/writer/splitter/JsonChunkDocumentProducer.java
- src/main/java/com/marklogic/spark/writer/splitter/XmlChunkDocumentProducer.java
- src/test/java/com/marklogic/spark/writer/splitter/SplitJsonDocumentTest.java
- src/test/java/com/marklogic/spark/writer/splitter/SplitTextDocumentTest.java
- src/test/java/com/marklogic/spark/writer/splitter/SplitXmlDocumentTest.java
Pull the JSON stuff out into `JsonChunkDocumentProcessor`. Added tests for max chunks for XML and Text.
> MLE-17222 Supporting max chunks for XML and Text source documents

- src/main/java/com/marklogic/spark/Options.java
- src/main/java/com/marklogic/spark/writer/DocumentProcessorFactory.java
- src/main/java/com/marklogic/spark/writer/splitter/AbstractChunkDocumentProducer.java
- src/main/java/com/marklogic/spark/writer/splitter/ChunkConfig.java
- src/main/java/com/marklogic/spark/writer/splitter/DefaultChunkAssembler.java
- src/main/java/com/marklogic/spark/writer/splitter/JsonChunkDocumentProducer.java
- src/main/java/com/marklogic/spark/writer/splitter/XmlChunkDocumentProducer.java
- src/test/java/com/marklogic/spark/writer/splitter/SplitJsonDocumentTest.java
- src/test/java/com/marklogic/spark/writer/splitter/SplitTextDocumentTest.java
- src/test/java/com/marklogic/spark/writer/splitter/SplitXmlDocumentTest.java
Did some refactoring too - added `AbstractChunkDocumentProducer` to capture common logic between JSON and XML.
> MLE-1722 Now supporting configurable document type for chunks

- src/main/java/com/marklogic/spark/writer/splitter/AbstractChunkDocumentProducer.java
- src/test/java/com/marklogic/spark/writer/splitter/SplitJsonDocumentTest.java
- src/test/java/com/marklogic/spark/writer/splitter/SplitTextDocumentTest.java
- src/test/java/com/marklogic/spark/writer/splitter/SplitXmlDocumentTest.java
1 seems more expected. Makes it easy to count how many chunk documents you have too.
> Chunk document URIs start at 1 instead of 0 now

- src/main/java/com/marklogic/spark/Options.java
- src/main/java/com/marklogic/spark/writer/DocumentProcessorFactory.java
- src/test/java/com/marklogic/spark/writer/splitter/SplitJsonDocumentTest.java
- src/test/java/com/marklogic/spark/writer/splitter/SplitTextDocumentTest.java
- src/test/java/com/marklogic/spark/writer/splitter/SplitXmlDocumentTest.java
"sidecar" is much more specific and the options are only used for sidecar documents.
> Renamed options to use "sidecar" instead of "output"

- src/main/java/com/marklogic/spark/Options.java
- src/main/java/com/marklogic/spark/writer/DocumentProcessorFactory.java
- src/main/java/com/marklogic/spark/writer/splitter/JDOMTextSelector.java
- src/test/java/com/marklogic/spark/writer/splitter/SplitXmlDocumentTest.java
Should be obvious for most users that it's specific to XML documents.
> Renaming "xml_path" to just "xpath"

- build.gradle
- src/main/java/com/marklogic/spark/Options.java
- src/main/java/com/marklogic/spark/writer/DocumentProcessorFactory.java
- src/main/java/com/marklogic/spark/writer/embedding/Chunk.java
- src/main/java/com/marklogic/spark/writer/embedding/EmbedderDocumentProcessorFactory.java
- src/main/java/com/marklogic/spark/writer/embedding/EmbeddingGenerator.java
- src/main/java/com/marklogic/spark/writer/embedding/JsonChunk.java
- src/main/java/com/marklogic/spark/writer/splitter/DefaultChunkAssembler.java
- src/main/java/com/marklogic/spark/writer/splitter/JsonChunkDocumentProducer.java
- src/main/java/com/marklogic/spark/writer/splitter/SplitterDocumentProcessorFactory.java
- src/test/java/com/marklogic/spark/writer/embedding/AddEmbeddingsToJsonTest.java
- src/test/java/com/marklogic/spark/writer/embedding/EmbedderTest.java
- src/test/java/com/marklogic/spark/writer/embedding/MinilmEmbeddingModelFunction.java
- src/test/ml-schemas-12/tde/json-vector-chunks.json
Little bit of refactoring in here - moved all the splitter factory stuff to a new class. Next PR will add support for adding embeddings when the documents have already had chunks written to them.
> MLE-17556 Can now generate embeddings for JSON chunks

- src/main/java/com/marklogic/spark/writer/splitter/DOMTextSelector.java
- src/main/java/com/marklogic/spark/writer/splitter/JsonPointerTextSelector.java
- src/test/java/com/marklogic/spark/writer/splitter/SplitJsonDocumentTest.java
- src/test/java/com/marklogic/spark/writer/splitter/SplitXmlDocumentTest.java
Ran into this with those annoying .DS_Store files in a zip.
> Logging warning when text cannot be split from document

- src/main/java/com/marklogic/spark/reader/file/ArchiveFileReader.java
- src/main/java/com/marklogic/spark/reader/file/FileBatch.java
- src/main/java/com/marklogic/spark/reader/file/FileContext.java
- src/main/java/com/marklogic/spark/reader/file/GenericFileReader.java
- src/main/java/com/marklogic/spark/reader/file/GzipFileReader.java
- src/main/java/com/marklogic/spark/reader/file/JsonLinesFileReader.java
- src/main/java/com/marklogic/spark/reader/file/MlcpArchiveFileReader.java
- src/main/java/com/marklogic/spark/reader/file/RdfFileReader.java
- src/main/java/com/marklogic/spark/reader/file/RdfZipFileReader.java
- src/main/java/com/marklogic/spark/reader/file/ZipFileReader.java
- src/main/java/com/marklogic/spark/reader/file/xml/AggregateXmlFileReader.java
- src/main/java/com/marklogic/spark/reader/file/xml/ZipAggregateXmlFileReader.java
- src/main/java/com/marklogic/spark/writer/DocumentRowConverter.java
- src/test/java/com/marklogic/spark/reader/file/ReadAggregateXmlZipFilesTest.java
- src/test/java/com/marklogic/spark/reader/file/ReadGenericFilesTest.java
- src/test/java/com/marklogic/spark/reader/file/ReadGzipAggregateXmlFilesTest.java
- src/test/java/com/marklogic/spark/reader/file/ReadGzipFilesTest.java
- src/test/java/com/marklogic/spark/writer/file/WriteArchiveTest.java
- src/test/java/com/marklogic/spark/writer/file/WriteDocumentZipFilesTest.java
- src/test/resources/generic-files/has+plus.json
Turns out we needed to use a different Spark API to get a list of files - the one we were using was surprisingly URL encoding all the file paths.
> MLE-17730 Fixed file path encoding issues

- src/main/java/com/marklogic/spark/writer/ArbitraryRowConverter.java
- src/main/java/com/marklogic/spark/writer/DocumentRowConverter.java
- src/main/java/com/marklogic/spark/writer/FileRowConverter.java
- src/main/java/com/marklogic/spark/writer/RowConverter.java
- src/main/java/com/marklogic/spark/writer/WriteBatcherDataWriter.java
- src/main/java/com/marklogic/spark/writer/rdf/RdfRowConverter.java
- src/test/java/com/marklogic/spark/AbstractIntegrationTest.java
Allows for `buildAndWriteDocuments` to be used both during the connector `write` and `commit` methods. This is primarily in preparation for the next PR, which changes how the embedder batch size works.
> Refactored RowConverter so that an Iterator is always returned

- src/main/java/com/marklogic/langchain4j/MarkLogicLangchainException.java
- src/main/java/com/marklogic/langchain4j/Util.java
- src/main/java/com/marklogic/langchain4j/dom/DOMHelper.java
- src/main/java/com/marklogic/langchain4j/dom/XPathNamespaceContext.java
- src/main/java/com/marklogic/langchain4j/embedding/DOMChunk.java
- src/main/java/com/marklogic/langchain4j/embedding/DOMChunkSelector.java
- src/main/java/com/marklogic/langchain4j/embedding/EmbeddingAdder.java
- src/main/java/com/marklogic/langchain4j/embedding/EmbeddingGenerator.java
- src/main/java/com/marklogic/langchain4j/embedding/JsonChunkSelector.java
- src/main/java/com/marklogic/langchain4j/splitter/DOMTextSelector.java
- src/main/java/com/marklogic/langchain4j/splitter/DefaultChunkAssembler.java
- src/main/java/com/marklogic/langchain4j/splitter/DocumentTextSplitter.java
- src/main/java/com/marklogic/langchain4j/splitter/JsonChunkDocumentProducer.java
- src/main/java/com/marklogic/langchain4j/splitter/JsonPointerTextSelector.java
- src/main/java/com/marklogic/spark/Util.java
- src/main/java/com/marklogic/spark/langchain4j/DocumentTextSplitterFactory.java
- src/main/java/com/marklogic/spark/langchain4j/EmbeddingAdderFactory.java
- src/main/java/com/marklogic/spark/langchain4j/NamespaceContextFactory.java
- src/test/java/com/marklogic/langchain4j/embedding/DOMChunkSelectorTest.java
- src/test/java/com/marklogic/langchain4j/embedding/EmbedderTest.java
- src/test/java/com/marklogic/spark/writer/splitter/SplitJsonDocumentTest.java
- src/test/java/com/marklogic/spark/writer/splitter/SplitXmlDocumentTest.java
This is to prepare for a move to multiple subprojects. The com.marklogic.langchain4j package now no longer has any references to com.marklogic.spark.
Still no functional changes, just moving furniture around.
> Refactor: Removed Spark connector references from langchain package

- marklogic-spark-connector/src/main/java/com/marklogic/spark/reader/optic/PlanAnalyzer.java
- marklogic-spark-connector/src/test/java/com/marklogic/spark/reader/optic/CalculatePartitionsTest.java
While researching the effects of batch size = zero, I realized that it would be better for the number of buckets per partition to be ceiling'ed to minimize the chance that any bucket has more rows than `batchSize`.
Added a test to verify the low-level functionality for calculating the number of partitions and buckets based on row count, the user-defined partition count, and the batch size.
> Tweaked calculation of buckets per partition

- marklogic-langchain4j/src/main/java/com/marklogic/langchain4j/embedding/EmbeddingAdder.java
- marklogic-spark-api/src/main/java/com/marklogic/spark/Context.java
- marklogic-spark-connector/src/main/java/com/marklogic/spark/ContextSupport.java
- marklogic-spark-connector/src/test/java/com/marklogic/langchain4j/embedding/EmbedderTest.java
- marklogic-spark-connector/src/test/java/com/marklogic/spark/writer/embedding/AddEmbeddingsToXmlTest.java
- marklogic-spark-langchain4j/src/main/java/com/marklogic/spark/langchain4j/EmbeddingAdderFactory.java
The constructors make the two different use cases more clear. Fixed an existing Sonar issue in Context too.
> Refactored EmbeddingAdder

- marklogic-langchain4j/src/main/java/com/marklogic/langchain4j/embedding/EmbeddingGenerator.java
- marklogic-spark-connector/src/test/java/com/marklogic/spark/writer/embedding/AddEmbeddingsToJsonTest.java
- marklogic-spark-connector/src/test/java/com/marklogic/spark/writer/embedding/TestEmbeddingModel.java
- marklogic-spark-langchain4j/src/main/java/com/marklogic/spark/langchain4j/EmbeddingAdderFactory.java
- test-app/src/main/ml-schemas-12/tde/json-vector-chunks.json
For now, "invalid" = a vector with all zeroes in it. Which Ollama seems to spit out intermittently. And MarkLogic can't do anything useful with it, and in fact it will throw an error, so we're not adding it.
> Not adding invalid embeddings

- docs/reading-data/optic.md
- marklogic-spark-connector/src/main/java/com/marklogic/spark/ContextSupport.java
- marklogic-spark-connector/src/main/java/com/marklogic/spark/reader/optic/OpticReadContext.java
- marklogic-spark-connector/src/main/java/com/marklogic/spark/reader/optic/PlanAnalysis.java
- marklogic-spark-connector/src/main/java/com/marklogic/spark/reader/optic/PlanAnalyzer.java
- marklogic-spark-connector/src/main/java/com/marklogic/spark/writer/WriteContext.java
- marklogic-spark-connector/src/test/java/com/marklogic/spark/reader/optic/AnalyzePlanTest.java
- marklogic-spark-connector/src/test/java/com/marklogic/spark/reader/optic/ReadWithAccessorOtherThanFromViewTest.java
- marklogic-spark-connector/src/test/java/com/marklogic/spark/reader/optic/SerializeOpticReaderObjectsTest.java
- test-app/src/main/ml-config/security/roles/spark-user-role.json
I moved a little code around to make the support for fromView and non-fromView a bit easier to digest:
1. Most changes are in `OpticReadContext` and `PlanAnalyzer`, which both needed support for making a single call for non-fromView queries.
2. I also moved the filter pushdown code into `PlanAnalysis` where it's closer to the data. And needed to account for whether the serialized plan has an `op:prepare` in it or not.
> Can now execute non-fromView queries

- marklogic-langchain4j/src/main/java/com/marklogic/langchain4j/Util.java
- marklogic-spark-connector/src/main/java/com/marklogic/spark/writer/DocBuilderFactory.java
- marklogic-spark-connector/src/main/java/com/marklogic/spark/writer/rdf/GraphWriter.java
- marklogic-spark-connector/src/test/java/com/marklogic/spark/writer/WriteRowsTest.java
- marklogic-spark-langchain4j/build.gradle
- marklogic-spark-langchain4j/src/main/java/com/marklogic/spark/langchain4j/DocumentTextSplitterFactory.java
Ran into this while testing sidecar permissions in Flux.
> Better error message for invalid permission capabilities

- Jenkinsfile
- build.gradle
- code-coverage-report/build.gradle
- docs/index.md
- marklogic-langchain4j/build.gradle
- marklogic-spark-connector/build.gradle
- marklogic-spark-connector/src/test/java/com/marklogic/spark/writer/splitter/SplitXmlDocumentTest.java
- settings.gradle
jacoco is producing the correct report in the `code-coverage-report` subproject, but sonarqube doesn't report the same numbers - i.e. 90% vs 77%.
> Hopefully fixing sonarqube code coverage

- marklogic-spark-connector/src/main/java/com/marklogic/spark/DefaultSource.java
- marklogic-spark-connector/src/main/java/com/marklogic/spark/reader/optic/OpticReadContext.java
- marklogic-spark-connector/src/test/java/com/marklogic/spark/reader/optic/ReadRowsTest.java
Ran into this while testing, as I was using an interval smaller than the batch size, which led to erroneous progress logging.
> Fixing progress logging issue for reading rows

- marklogic-langchain4j/build.gradle
- marklogic-spark-connector/build.gradle
- marklogic-spark-connector/src/main/java/com/marklogic/spark/reader/customcode/CustomCodeScan.java
Ran into this while testing the Java Client change in Flux. No tests, the only indication this happens is a log message from OkHttp (which oddly does not appear in the tests here, but does appear in Flux).
> Fixing memory leak with eval call

- marklogic-spark-connector/src/test/java/com/marklogic/spark/writer/embedding/AddEmbeddingsToJsonTest.java
- marklogic-spark-connector/src/test/java/com/marklogic/spark/writer/embedding/AddEmbeddingsToXmlTest.java
- marklogic-spark-connector/src/test/java/com/marklogic/spark/writer/splitter/SplitXmlDocumentTest.java
For XML, it doesn't matter if the element already exists since we're doing an `appendChild`.
For JSON - it does matter if the property name already exists. The splitter then uses "splitter-chunks" as the name. I think we can take the same approach for the classifier so we avoid the need for two more options. May later change the embedder to follow the same pattern.
> Added splitter test and some messages about embedding customizations

- marklogic-spark-connector/src/main/java/com/marklogic/spark/reader/document/DocumentRowSchema.java
- marklogic-spark-connector/src/main/java/com/marklogic/spark/writer/WriteBatcherDataWriter.java
- marklogic-spark-connector/src/main/java/com/marklogic/spark/writer/WriteContext.java
- marklogic-spark-connector/src/main/java/com/marklogic/spark/writer/document/DocumentRow.java
- marklogic-spark-connector/src/main/java/com/marklogic/spark/writer/document/DocumentRowConverter.java
Intent is to avoid bloat in DocumentRowConverter and provide a nice OO wrapper around an InternalRow that represents a document. Will be useful for upcoming methods for getting chunks and classification data and embeddings from a row.
> Refactor: Added DocumentRow

- marklogic-spark-connector/src/main/java/com/marklogic/spark/writer/DocBuilder.java
- marklogic-spark-connector/src/main/java/com/marklogic/spark/writer/DocBuilderFactory.java
- marklogic-spark-connector/src/main/java/com/marklogic/spark/writer/WriteBatcherDataWriter.java
- marklogic-spark-connector/src/main/java/com/marklogic/spark/writer/WriteContext.java
- marklogic-spark-connector/src/main/java/com/marklogic/spark/writer/document/DocumentRow.java
- marklogic-spark-connector/src/main/java/com/marklogic/spark/writer/document/DocumentRowConverter.java
Intent is to capture all the inputs from a Spark row in a DocumentInputs class, and then DocBuilder has all the smarts for building 1 or more documents.
> Refactor: Moved doc construction to DocBuilder

- marklogic-spark-api/src/main/java/com/marklogic/spark/Context.java
- marklogic-spark-connector/src/main/java/com/marklogic/spark/udf/TextSplitter.java
- marklogic-spark-connector/src/main/java/com/marklogic/spark/udf/TextSplitterConfig.java
- marklogic-spark-connector/src/test/java/com/marklogic/spark/IOExceptionTestExecutionListener.java
- marklogic-spark-connector/src/test/java/com/marklogic/spark/writer/document/WriteExtractedTextTest.java
- marklogic-spark-connector/src/test/java/com/marklogic/spark/writer/splitter/SplitJsonDocumentTest.java
- marklogic-spark-langchain4j/src/main/java/com/marklogic/spark/langchain4j/DocumentTextSplitterFactory.java
This doesn't test all of the options yet. Will get tests in place later. Want to get all 4 processors built out first to make sure it all works nicely.
This sets what seems like a reasonable pattern for constructing UDFs that have non-serializable dependencies as well.
> Added all splitter config options

- marklogic-langchain4j/src/main/java/com/marklogic/langchain4j/classifier/TextClassifier.java
- marklogic-spark-connector/build.gradle
- marklogic-spark-connector/src/main/java/com/marklogic/spark/udf/TextClassifierUdf.java
- marklogic-spark-connector/src/main/java/com/marklogic/spark/writer/DocBuilder.java
- marklogic-spark-connector/src/main/java/com/marklogic/spark/writer/document/DocumentRow.java
- marklogic-spark-connector/src/main/java/com/marklogic/spark/writer/document/DocumentRowConverter.java
- marklogic-spark-connector/src/test/java/com/marklogic/spark/writer/classifier/AddClassificationToXmlTest.java
New attempt. This one uses the newly implemented DocBuilder.
> Can now use a classifier UDF to classifier top-level documents with XML content.

- marklogic-spark-connector/src/main/java/com/marklogic/spark/udf/TextSplitterConfig.java
- marklogic-spark-connector/src/test/java/com/marklogic/spark/writer/splitter/SplitJsonDocumentTest.java
We want a nicer interface for UDF users, as they aren't constrained by only specifying values as strings. Makes life easier for Flux too.
> Tweak to splitter UDF

- marklogic-langchain4j/build.gradle
- marklogic-langchain4j/src/main/java/com/marklogic/langchain4j/Util.java
- marklogic-langchain4j/src/main/java/com/marklogic/langchain4j/embedding/DOMChunkSelector.java
- marklogic-langchain4j/src/main/java/com/marklogic/langchain4j/embedding/JsonChunkSelector.java
- marklogic-langchain4j/src/main/java/com/marklogic/langchain4j/embedding/XmlChunkConfig.java
- marklogic-langchain4j/src/main/java/com/marklogic/langchain4j/splitter/ChunkConfig.java
- marklogic-langchain4j/src/main/java/com/marklogic/langchain4j/splitter/DOMTextSelector.java
- marklogic-langchain4j/src/main/java/com/marklogic/langchain4j/splitter/DefaultChunkAssembler.java
- marklogic-langchain4j/src/main/java/com/marklogic/langchain4j/splitter/JsonChunkDocumentProducer.java
- marklogic-langchain4j/src/main/java/com/marklogic/langchain4j/splitter/JsonPointerTextSelector.java
- marklogic-langchain4j/src/main/java/com/marklogic/langchain4j/splitter/XmlChunkDocumentProducer.java
- marklogic-spark-api/build.gradle
- marklogic-spark-api/src/main/java/com/marklogic/spark/Util.java
- marklogic-spark-api/src/main/java/com/marklogic/spark/dom/DOMHelper.java
- marklogic-spark-api/src/main/java/com/marklogic/spark/dom/XPathNamespaceContext.java
- marklogic-spark-connector/src/main/java/com/marklogic/spark/writer/DocBuilder.java
- marklogic-spark-connector/src/main/java/com/marklogic/spark/writer/DocBuilderFactory.java
- marklogic-spark-connector/src/main/java/com/marklogic/spark/writer/rdf/GraphWriter.java
- marklogic-spark-connector/src/test/java/com/marklogic/langchain4j/embedding/EmbedderTest.java
- marklogic-spark-connector/src/test/java/com/marklogic/spark/writer/splitter/SplitXmlDocumentTest.java
- marklogic-spark-langchain4j/src/main/java/com/marklogic/spark/langchain4j/DocumentTextSplitterFactory.java
- marklogic-spark-langchain4j/src/main/java/com/marklogic/spark/langchain4j/NamespaceContextFactory.java
That module is going to require Java 17. Still have a few things left to fix, but this takes care of some easy stuff by moving things into marklogic-spark-api.
> Minimizing dependency on marklogic-langchain4j module

- marklogic-spark-api/src/main/java/com/marklogic/spark/Options.java
- marklogic-spark-api/src/main/java/com/marklogic/spark/core/classifier/TextClassifier.java
- marklogic-spark-api/src/main/java/com/marklogic/spark/core/classifier/TextClassifierFactory.java
- tests/src/test/java/com/marklogic/spark/writer/classifier/AddClassificationToJsonTest.java
- tests/src/test/java/com/marklogic/spark/writer/classifier/AddClassificationToXmlTest.java
- tests/src/test/java/com/marklogic/spark/writer/classifier/ConfigHelperTest.java
Also renamed from "endpoint" to "path" for alignment with the S4 config class and the Java URL class.
Added some debug logging as well.
> Made it easier to config classifier paths

- marklogic-spark-connector/src/main/java/com/marklogic/spark/writer/WriteContext.java
- tests/build.gradle
- tests/src/test/java/com/marklogic/spark/writer/document/WriteExtractedTextTest.java
The regular permissions are now inherited when user specifies collections but not permissions for extracted text doc.
> Fixed bug with extracted text permissions

- marklogic-spark-api/src/main/java/com/marklogic/spark/core/DocumentProcessor.java
- marklogic-spark-api/src/main/java/com/marklogic/spark/core/classifier/SemaphoreTextClassifier.java
- marklogic-spark-api/src/main/java/com/marklogic/spark/core/classifier/SemaphoreUtil.java
- marklogic-spark-api/src/main/java/com/marklogic/spark/core/classifier/TextClassifier.java
- marklogic-spark-api/src/main/java/com/marklogic/spark/core/classifier/TextClassifierFactory.java
- marklogic-spark-api/src/main/java/com/marklogic/spark/core/splitter/JsonChunkDocumentProducer.java
- marklogic-spark-api/src/main/java/com/marklogic/spark/core/splitter/XmlChunkDocumentProducer.java
- marklogic-spark-connector/src/main/java/com/marklogic/spark/writer/DocBuilder.java
- tests/src/test/java/com/marklogic/spark/writer/classifier/AddClassificationToJsonTest.java
- tests/src/test/java/com/marklogic/spark/writer/classifier/AddClassificationToXmlTest.java
- tests/src/test/java/com/marklogic/spark/writer/classifier/ClassifierTestUtil.java
- tests/src/test/java/com/marklogic/spark/writer/classifier/ConfigHelperTest.java
Turned TextClassifier into an interface to support this, with SemaphoreTextClassifier having the goods in it now. Added a few more S4 config tests to ensure we build a connection correctly, as none of the tests now depend on an active S4 connection. A couple tests still have the "live" options for easy manual testing though.
Removed the two disabled UTF-8 tests as we no longer have any code that constructs a String from bytes.
> Classifier tests now use a mock

- marklogic-spark-connector/build.gradle
This may fix a longstanding issue where using flux-api in a context that also wants to use the Java Client runs into issues. This seems to be a necessary fix for ragplus.
> Shadowing the Java Client

- marklogic-langchain4j/src/main/java/com/marklogic/langchain4j/embedding/EmbeddingGenerator.java
- marklogic-spark-api/src/main/java/com/marklogic/spark/Options.java
- marklogic-spark-api/src/main/java/com/marklogic/spark/core/DocumentInputs.java
- marklogic-spark-api/src/main/java/com/marklogic/spark/core/DocumentProcessor.java
- marklogic-spark-api/src/main/java/com/marklogic/spark/core/classifier/SemaphoreTextClassifier.java
- marklogic-spark-api/src/main/java/com/marklogic/spark/core/classifier/TextClassifier.java
- marklogic-spark-api/src/main/java/com/marklogic/spark/core/classifier/TextClassifierFactory.java
- marklogic-spark-api/src/main/java/com/marklogic/spark/core/embedding/EmbeddingProducer.java
- marklogic-spark-connector/src/main/java/com/marklogic/spark/writer/WriteBatcherDataWriter.java
- tests/src/test/java/com/marklogic/spark/writer/embedding/AddEmbeddingsToJsonTest.java
Summary:
- The WriteBatcherDataWriter (DW) now batches documents up until it has N.
- It then passes N documents to the DocumentProcessor (DP).
- The DP then fully processes everything in the batch.
This doesn't do batching yet for S4 though. I started down that road, and it's a lot more changes, so tossed that on a separate branch so this can be a straight refactor (notice that none of the tests changed, except I enhanced one to make more assertions).
> Refactor: Overhauling how batching works for document processing

- marklogic-spark-api/src/main/java/com/marklogic/spark/core/extraction/ExtractionUtil.java
- marklogic-spark-connector/src/main/java/com/marklogic/spark/writer/DocBuilder.java
- tests/src/test/java/com/marklogic/spark/AbstractIntegrationTest.java
- tests/src/test/java/com/marklogic/spark/writer/document/WriteExtractedTextTest.java
Not possible in JSON, but this spruces up the XML into something more useful.
> Using well-known namespaces for Tika XML metadata

- marklogic-spark-connector/src/main/java/com/marklogic/spark/writer/DocBuilder.java
- tests/src/test/java/com/marklogic/spark/writer/classifier/ClassifyExtractedTextTest.java
- tests/src/test/java/com/marklogic/spark/writer/document/WriteExtractedTextTest.java
This reverts commit 1de4b7415c8ad558f5d8d63bd0b995ac41c46160.
This is very likely to cause issues when exporting documents, as it will produce a file and a directory with the same name.
> Revert "Adjusting extracted text URI"

- marklogic-spark-api/src/main/java/com/marklogic/spark/core/splitter/AbstractChunkDocumentProducer.java
- marklogic-spark-api/src/main/java/com/marklogic/spark/core/splitter/ChunkAssembler.java
- marklogic-spark-api/src/main/java/com/marklogic/spark/core/splitter/DefaultChunkAssembler.java
- marklogic-spark-api/src/main/java/com/marklogic/spark/core/splitter/JsonChunkDocumentProducer.java
- marklogic-spark-api/src/main/java/com/marklogic/spark/core/splitter/XmlChunkDocumentProducer.java
- marklogic-spark-connector/src/main/java/com/marklogic/spark/writer/DocBuilder.java
- tests/src/test/java/com/marklogic/spark/writer/embedding/AddEmbeddingsFromTextTest.java
Refactor ChunkAssembler to have embeddings list passed for chunk construction.
Refactor XML and JSON producers to add the embeddings to the chunks as they are built. Add two test to ensure different text chunks do not have the same embedding vector for JSON and XML document formats.
> Bug MLE-20704 - incorrect embeddings stored for chunk documents.

- marklogic-spark-api/src/main/java/com/marklogic/spark/Util.java
- tests/src/test/java/com/marklogic/spark/writer/WriteRowsTest.java
- tests/src/test/java/com/marklogic/spark/writer/document/WriteExtractedTextTest.java
And improved the error by not including the original error, which isn't needed. Just need the "clean" error message that won't be confusing to a Flux user.
> Added test for invalid extracted text permissions

- marklogic-spark-api/src/main/java/com/marklogic/spark/core/classifier/TextClassifierFactory.java
- tests/src/test/java/com/marklogic/spark/core/classifier/ConfigHelperTest.java
Useful for local environments. Also avoids an ugly null-pointer error when not specified.
> Default the classifier path to "/"

- CONTRIBUTING.md
- docs/index.md
- examples/entity-aggregation/build.gradle
- examples/java-dependency/build.gradle
- gradle.properties
This should be a no-op for the connector, just staying up-to-date with the latest public release of Spark. Will bump Flux next.
> Building and testing against Spark 3.5.5

- CONTRIBUTING.md
- tests/build.gradle
add-exports only exposes public members, which should suffice for the tests.
> Using add-exports instead of add-opens

- tests/build.gradle
The tests already depend on Java 17, so we can use the latest logback version to minimize vulnerabilities.
> Bumped logging dependency

- marklogic-spark-api/src/main/java/com/marklogic/spark/core/classifier/SemaphoreProxy.java
- marklogic-spark-api/src/main/java/com/marklogic/spark/core/classifier/SemaphoreProxyImpl.java
- marklogic-spark-api/src/main/java/com/marklogic/spark/core/classifier/SemaphoreTextClassifier.java
- marklogic-spark-api/src/main/java/com/marklogic/spark/core/classifier/TextClassifierFactory.java
- tests/src/test/java/com/marklogic/spark/writer/classifier/AddClassificationToJsonTest.java
- tests/src/test/java/com/marklogic/spark/writer/classifier/AddClassificationToXmlTest.java
- tests/src/test/java/com/marklogic/spark/writer/classifier/ClassifyExtractedTextTest.java
Avoids confusion over use of "MultiArticle". Main use case for this is to hide the actual call to Semaphore so it can be mocked easily.
> Refactor: Renamed to SemaphoreProxy

- marklogic-spark-api/src/main/java/com/marklogic/spark/Options.java
- marklogic-spark-api/src/main/java/com/marklogic/spark/core/embedding/ChunkSelectorFactory.java
- marklogic-spark-api/src/main/java/com/marklogic/spark/core/splitter/ChunkAssemblerFactory.java
- tests/src/test/java/com/marklogic/spark/writer/embedding/AddEmbeddingsToJsonTest.java
- tests/src/test/java/com/marklogic/spark/writer/embedding/AddEmbeddingsToXmlTest.java
The use of "embedder" in the option name makes it clear that we're talking about base64 encoding of the vector. The underlying variables still say "base64EncodeVectors" to make it obvious what they refer to.
> MLE-22889 Renamed base64 option

- marklogic-spark-connector/src/main/java/com/marklogic/spark/writer/ArbitraryRowConverter.java
- tests/src/test/java/com/marklogic/spark/writer/embedding/AddEmbeddingsToJsonTest.java
Using "/temporary/(UUID)" resulted in the "/temporary" being retained if no URI modification option was provided.
> MLE-22784 Using just a UUID as a temporary URI

- build.gradle
- gradle.properties
- marklogic-spark-connector/build.gradle
- marklogic-spark-connector/src/main/java/com/marklogic/spark/DefaultSource.java
- marklogic-spark-connector/src/main/java/com/marklogic/spark/JsonRowSerializer.java
- marklogic-spark-connector/src/main/java/com/marklogic/spark/MarkLogicFileTable.java
- marklogic-spark-connector/src/main/java/com/marklogic/spark/reader/JsonRowDeserializer.java
- marklogic-spark-connector/src/main/java/com/marklogic/spark/reader/document/OpticTriplesReader.java
- marklogic-spark-connector/src/main/java/com/marklogic/spark/reader/file/RdfZipFileReader.java
- marklogic-spark-connector/src/main/java/com/marklogic/spark/writer/file/ContentWriter.java
- tests/build.gradle
- tests/src/test/java/com/marklogic/spark/AbstractIntegrationTest.java
- tests/src/test/java/com/marklogic/spark/reader/document/ReadDocumentRowsWithMetadataTest.java
- tests/src/test/java/com/marklogic/spark/reader/file/ReadArchiveFileTest.java
- tests/src/test/java/com/marklogic/spark/reader/file/ReadMlcpArchiveFilesTest.java
- tests/src/test/java/com/marklogic/spark/reader/optic/AbstractPushDownTest.java
- tests/src/test/java/com/marklogic/spark/reader/optic/GroupByDuplicateColumnNamesTest.java
- tests/src/test/java/com/marklogic/spark/writer/WriteArchiveOfFailedDocumentsTest.java
- tests/src/test/java/com/marklogic/spark/writer/WriteStreamOfRowsTest.java
This reverts commit 678c21dcf12123b7ae7133e08e30de7faf9d137c, reversing
changes made to ba227c715ceba66dc8b6d43ff563484f9414a53d.
> MLE-23024 Revert prior PR

- NOTICE.txt
- build.gradle
- gradle.properties
- marklogic-langchain4j/build.gradle
- marklogic-spark-api/build.gradle
- marklogic-spark-api/src/main/java/com/marklogic/spark/core/classifier/TextClassifierFactory.java
- tests/build.gradle
The main bump here is jena-arq to 5.5.0, which requires Java 17. Which is fine to do now that Spark 4 is being used.
> MLE-23024 Bumping more dependencies for Spark 4

- test-app/build.gradle
- tests/build.gradle
This only impacts the test runtime, not the connector. And it will remove a set of medium vulnerabilities in Black Duck that originated from Spring 5.
> MLE-22951 Using ml-gradle 6

- marklogic-spark-connector/src/main/java/com/marklogic/spark/writer/file/FileUtil.java
- tests/src/test/java/com/marklogic/spark/writer/file/FileUtilTest.java
- tests/src/test/java/com/marklogic/spark/writer/file/WriteDocumentZipFilesTest.java
Turns out we still need this behavior for the ordinary case of writing a URI to a file where the URI has a scheme in it. This doesn't impact zip files though.
> MLE-23330 Trimming off scheme when writing URIs to files

- marklogic-spark-connector/build.gradle
It's not in Spark 4, so don't need this shading anymore.
> MLE-24402 No longer needed to shade OkHttp

- build.gradle
- marklogic-spark-connector/build.gradle
This only affects the tests, as the connector doesn't include zookeeper
> MLE-24494 Bumped zookeeper to 3.9.4
