marklogic/marklogic-spark-connector

CONTRIBUTING.md
Dockerfile
build.gradle
docker-compose.yaml
gradle.properties
src/test/java/com/marklogic/spark/reader/GetDataHostsTest.java
src/test/java/com/marklogic/spark/reader/PerformanceTester.java
src/test/ml-data/allTypes-data.json

See the CONTRIB file on instructions on how to try this out locally.

Added 3-node testing support via Docker

---

docs/reading.md
src/main/java/com/marklogic/spark/reader/MarkLogicPartitionReader.java
src/main/java/com/marklogic/spark/reader/PlanAnalyzer.java
src/main/java/com/marklogic/spark/reader/ReadContext.java
src/test/java/com/marklogic/spark/reader/AnalyzePlanTest.java
src/test/java/com/marklogic/spark/reader/PerformanceTester.java
src/test/java/com/marklogic/spark/reader/ReadRowsTest.java

Allows for a single request per partition. Added more docs and logging to help user understand what's going on too.

DEVEXP-432 User can now set batchSize to zero

---

docs/configuration.md
src/main/java/com/marklogic/spark/ContextSupport.java
src/main/java/com/marklogic/spark/Options.java
src/main/java/com/marklogic/spark/reader/ReadContext.java
src/main/java/com/marklogic/spark/writer/MarkLogicBatchWrite.java
src/main/java/com/marklogic/spark/writer/MarkLogicDataWriter.java
src/main/java/com/marklogic/spark/writer/WriteContext.java
src/test/java/com/marklogic/spark/writer/WriteRowsTest.java
src/test/ml-config/security/roles/spark-user-role.json
src/test/ml-config/security/users/spark-no-write-user.json

Going to merge ReadConstants into Options in a follow up PR.

DEVEXP-435 Now writing in batches via WriteBatcher

---

docs/reading.md
docs/writing.md

Really not a lot to say here, other than errors being thrown to the user with hopefully helpful error messages.

DEVEXP-457 Added docs for error handling

---

build.gradle

A note will be added to the docs as well for this, but in a future PR as I'm reorganizing the docs in a separate PR right now.

Added support for running tests on Java 17

---

src/main/java/com/marklogic/spark/MarkLogicTable.java

This is based on Mongo's connector, which simply does "MongoTable()". We don't really have a good input here, as there's no consistent "table" concept across read/write operations.

Added name() implementation

---

docs/configuration.md
docs/reading.md
docs/writing.md
src/main/java/com/marklogic/spark/reader/MarkLogicMicroBatchStream.java
src/main/java/com/marklogic/spark/reader/PlanAnalysis.java
src/main/java/com/marklogic/spark/reader/ReadContext.java
src/test/java/com/marklogic/spark/reader/AbstractPushDownTest.java
src/test/java/com/marklogic/spark/reader/MergeBucketsTest.java
src/test/java/com/marklogic/spark/reader/PushDownFilterTest.java
src/test/java/com/marklogic/spark/reader/PushDownFilterValueTypesTest.java
src/test/java/com/marklogic/spark/reader/PushDownGroupByMaxTest.java
src/test/java/com/marklogic/spark/reader/PushDownOrderByAndLimitTest.java

Also changed default batch size to 100k.

DEVEXP-488 Setting batch size to zero when pushing down aggregate

---

docs/configuration.md
src/main/java/com/marklogic/spark/ContextSupport.java
src/main/java/com/marklogic/spark/Options.java
src/test/java/com/marklogic/spark/BuildConnectionPropertiesTest.java

Having to set sslProtocol was bothering me because I don't think there's any way for something besides "default" to work.

Simplifying SSL configuration

---

docker-compose.yaml
src/main/java/com/marklogic/spark/ContextSupport.java
src/main/java/com/marklogic/spark/CustomCodeContext.java
src/main/java/com/marklogic/spark/DefaultSource.java
src/main/java/com/marklogic/spark/MarkLogicTable.java
src/main/java/com/marklogic/spark/Options.java
src/main/java/com/marklogic/spark/Util.java
src/main/java/com/marklogic/spark/reader/CustomCodeBatch.java
src/main/java/com/marklogic/spark/reader/CustomCodePartition.java
src/main/java/com/marklogic/spark/reader/CustomCodePartitionReader.java
src/main/java/com/marklogic/spark/reader/CustomCodePartitionReaderFactory.java
src/main/java/com/marklogic/spark/reader/CustomCodeScan.java
src/main/java/com/marklogic/spark/reader/CustomCodeScanBuilder.java
src/test/java/com/marklogic/spark/AbstractIntegrationTest.java
src/test/java/com/marklogic/spark/reader/ReadWithCustomCodeTest.java
src/test/ml-config/security/roles/spark-user-role.json
src/test/ml-modules/root/getAuthorObjects.sjs
src/test/ml-modules/root/getAuthors.sjs
src/test/ml-modules/root/getAuthors.xqy
src/test/resources/logback.xml

Will have a follow-up PR to rename the "MarkLogic*" reader classes to be "Optic*" instead.

DEVEXP-599 Can now read rows via custom code

---

docs/writing.md
src/main/java/com/marklogic/spark/ContextSupport.java
src/main/java/com/marklogic/spark/CustomCodeContext.java
src/main/java/com/marklogic/spark/Options.java
src/main/java/com/marklogic/spark/Util.java
src/main/java/com/marklogic/spark/reader/CustomCodePartitionReader.java
src/main/java/com/marklogic/spark/reader/CustomCodeScanBuilder.java
src/main/java/com/marklogic/spark/writer/CustomCodeWriter.java
src/main/java/com/marklogic/spark/writer/CustomCodeWriterFactory.java
src/main/java/com/marklogic/spark/writer/MarkLogicWrite.java
src/test/java/com/marklogic/spark/writer/ProcessMultipleRowsWithCustomCodeTest.java
src/test/ml-modules/root/processMultipleObjects.sjs
src/test/ml-modules/root/processMultipleUris.sjs
src/test/ml-modules/root/processMultipleUrisCustomDelimiter.sjs

Had to move some things around to implement this - the actual implementation isn't really much, it's just some code in CustomCodeWriter for creating either a delimited string or a JSON array.

DEVEXP-602 Can now process multiple rows per call

---

docs/reading.md

I decided on "read.stream." as the prefix for the new options. While I think "bulk" is good in a MarkLogic context, this is really a Spark feature we're implementing, so I chose "stream".

Added docs to spec out streaming support for custom code

---

examples/entity-aggregation/docker-compose.yml
src/main/java/com/marklogic/spark/writer/CustomCodeWriter.java
src/main/java/com/marklogic/spark/writer/CustomCodeWriterFactory.java
src/main/java/com/marklogic/spark/writer/MarkLogicWrite.java
src/main/java/com/marklogic/spark/writer/WriteBatcherDataWriter.java
src/test/java/com/marklogic/spark/reader/ReadStreamWithCustomCodeTest.java
src/test/java/com/marklogic/spark/writer/ProcessStreamWithCustomCodeTest.java

Will do the docs in a follow-up PR.

DEVEXP-652 Can now process a stream with custom code

---

docs/configuration.md
docs/getting-started/pyspark.md
docs/getting-started/setup.md
docs/reading.md
docs/writing.md
examples/getting-started/.gitignore
examples/getting-started/docker-compose.yml
examples/getting-started/gradle.properties
examples/getting-started/marklogic-spark-getting-started.ipynb

Changed port to 8003. Also added content on streaming writes with custom code.

DEVEXP-625 Reworked docs to use docker-compose

---

.gitignore
CONTRIBUTING.md
build.gradle
docker-compose-3nodes.yaml
docker-compose.yaml

Keeping separate file for 3-node cluster until DBQ-710 is resolved.

Changing docker-compose to default to single node

---

docs/getting-started/jupyter.md
docs/getting-started/pyspark.md
docs/reading.md
docs/writing.md
examples/entity-aggregation/build.gradle
examples/getting-started/build.gradle
examples/getting-started/gradle/wrapper/gradle-wrapper.properties
examples/getting-started/marklogic-spark-getting-started.ipynb
examples/java-dependency/build.gradle

Included bit about needing eval/invoke privileges for the new custom code feature.

Updating docs for 2.1.0

---

src/main/java/com/marklogic/spark/MarkLogicTable.java
src/main/java/com/marklogic/spark/reader/JsonRowDeserializer.java
src/main/java/com/marklogic/spark/reader/customcode/CustomCodeBatch.java
src/main/java/com/marklogic/spark/reader/customcode/CustomCodeContext.java
src/main/java/com/marklogic/spark/reader/customcode/CustomCodeMicroBatchStream.java
src/main/java/com/marklogic/spark/reader/customcode/CustomCodePartition.java
src/main/java/com/marklogic/spark/reader/customcode/CustomCodePartitionReader.java
src/main/java/com/marklogic/spark/reader/customcode/CustomCodePartitionReaderFactory.java
src/main/java/com/marklogic/spark/reader/customcode/CustomCodeScan.java
src/main/java/com/marklogic/spark/reader/customcode/CustomCodeScanBuilder.java
src/main/java/com/marklogic/spark/writer/MarkLogicWrite.java
src/main/java/com/marklogic/spark/writer/customcode/CustomCodeWriter.java
src/main/java/com/marklogic/spark/writer/customcode/CustomCodeWriterFactory.java
src/test/java/com/marklogic/spark/reader/customcode/ReadStreamWithCustomCodeTest.java
src/test/java/com/marklogic/spark/reader/customcode/ReadWithCustomCodeTest.java
src/test/java/com/marklogic/spark/writer/AbstractWriteTest.java
src/test/java/com/marklogic/spark/writer/customcode/ProcessMultipleRowsWithCustomCodeTest.java
src/test/java/com/marklogic/spark/writer/customcode/ProcessStreamWithCustomCodeTest.java
src/test/java/com/marklogic/spark/writer/customcode/ProcessWithCustomCodeTest.java

This is to prepare for the new readers/writers we'll be adding in 2.2. No change in functionality, just moving classes and tests.

Refactored custom-code feature into `customcode` package

---

docs/configuration.md

These are inherited via Java Client 6.4.0.

Added docs for new SSL properties

---

CONTRIBUTING.md
docs/configuration.md
docs/getting-started/pyspark.md
docs/reading.md
docs/writing.md
src/main/java/com/marklogic/spark/DefaultSource.java
src/main/resources/META-INF/services/org.apache.spark.sql.sources.DataSourceRegister
src/test/java/com/marklogic/spark/AbstractIntegrationTest.java
src/test/java/com/marklogic/spark/TestProgram.java
src/test/java/com/marklogic/spark/reader/PerformanceTester.java
src/test/python/test_program.py

Discovered this while looking at another connector's codebase.

Added short name support

---

src/main/java/com/marklogic/spark/DefaultSource.java
src/main/java/com/marklogic/spark/Options.java
src/main/java/com/marklogic/spark/reader/document/DocumentContext.java
src/main/java/com/marklogic/spark/reader/document/ForestReader.java
src/main/java/com/marklogic/spark/reader/document/SearchQueryBuilder.java
src/test/java/com/marklogic/spark/AbstractIntegrationTest.java
src/test/java/com/marklogic/spark/reader/document/BuildSearchQueryTest.java
src/test/java/com/marklogic/spark/reader/document/ReadDocumentRowsTest.java
src/test/java/com/marklogic/spark/reader/optic/ReadRowsMultipleTimesTest.java
src/test/java/com/marklogic/spark/reader/optic/ReadRowsWithBasicAuthTest.java
src/test/java/com/marklogic/spark/reader/optic/ReadWithJoinDocTest.java
src/test/java/com/marklogic/spark/reader/optic/SerializeOpticReaderObjectsTest.java
src/test/java/com/marklogic/spark/writer/file/WriteDocumentFilesTest.java
src/test/java/com/marklogic/spark/writer/file/WriteZipFilesTest.java
src/test/ml-config/databases/content-database.json
src/test/ml-data/dummy.xml
src/test/ml-modules/options/test-options.xml

Did a little test refactoring - added `objectMapper` to parent test class.

MLE-11896 Provided remaining search features for reading documents

---

src/main/java/com/marklogic/spark/reader/document/DocumentBatch.java
src/main/java/com/marklogic/spark/reader/document/DocumentContext.java
src/main/java/com/marklogic/spark/reader/document/DocumentScan.java
src/main/java/com/marklogic/spark/reader/document/DocumentScanBuilder.java
src/main/java/com/marklogic/spark/reader/document/ForestReader.java
src/test/java/com/marklogic/spark/reader/document/PushDownLimitTest.java

No functional change, just far better performance.

MLE-12257 Pushing down limit

---

src/main/java/com/marklogic/spark/DefaultSource.java
src/main/java/com/marklogic/spark/Util.java
src/main/java/com/marklogic/spark/reader/customcode/CustomCodeMicroBatchStream.java
src/main/java/com/marklogic/spark/reader/document/ForestReader.java
src/main/java/com/marklogic/spark/reader/optic/OpticMicroBatchStream.java
src/main/java/com/marklogic/spark/reader/optic/OpticPartitionReaderFactory.java
src/main/java/com/marklogic/spark/reader/optic/OpticScanBuilder.java
src/main/java/com/marklogic/spark/reader/optic/PlanUtil.java
src/main/java/com/marklogic/spark/reader/optic/ReadContext.java
src/main/java/com/marklogic/spark/reader/optic/SchemaInferrer.java
src/main/java/com/marklogic/spark/writer/MarkLogicWrite.java
src/main/java/com/marklogic/spark/writer/WriteBatcherDataWriter.java
src/main/java/com/marklogic/spark/writer/WriteContext.java
src/main/java/com/marklogic/spark/writer/customcode/CustomCodeWriter.java
src/test/resources/logback.xml

Introduced a "main" logger and made a few other tweaks based on testing. No functional changes here.

MLE-12294 Improving logging for sake of ETL tool

---

docs/reading-data/documents.md
src/main/java/com/marklogic/spark/ContextSupport.java
src/main/java/com/marklogic/spark/reader/document/ForestPartition.java
src/main/java/com/marklogic/spark/reader/document/ForestPartitionPlanner.java
src/main/java/com/marklogic/spark/reader/document/ForestReader.java
src/test/java/com/marklogic/spark/ContextSupportTest.java
src/test/java/com/marklogic/spark/reader/document/ReadDocumentRowsTest.java

Requires that the user explicitly set the connection type to `direct`.

MLE-12219 Can now create direct connections to hosts

---

src/main/java/com/marklogic/spark/reader/document/ForestReader.java
src/main/java/com/marklogic/spark/writer/CommitMessage.java
src/main/java/com/marklogic/spark/writer/MarkLogicWrite.java
src/main/java/com/marklogic/spark/writer/WriteBatcherDataWriter.java
src/main/java/com/marklogic/spark/writer/customcode/CustomCodeWriter.java

No functional change, just realized this is nice to see in the ETL tool.

Added logging of how many documents were written

---

src/main/java/com/marklogic/spark/writer/CommitMessage.java
src/main/java/com/marklogic/spark/writer/MarkLogicWrite.java
src/main/java/com/marklogic/spark/writer/WriteBatcherDataWriter.java
src/main/java/com/marklogic/spark/writer/customcode/CustomCodeWriter.java
src/test/java/com/marklogic/spark/writer/WriteRowsTest.java
src/test/java/com/marklogic/spark/writer/customcode/ProcessWithCustomCodeTest.java

May tweak this further, but this now correctly captures the counts. Added a little hook so we can write assertions on the counts too.

MLE-12357 Improved logging of success/failure counts

---

build.gradle
src/main/java/com/marklogic/spark/writer/MarkLogicWrite.java
src/main/java/com/marklogic/spark/writer/WriteContext.java
src/test/java/com/marklogic/spark/writer/WriteRowsTest.java
src/test/java/com/marklogic/spark/writer/customcode/ProcessWithCustomCodeTest.java
src/test/java/com/marklogic/spark/writer/document/WriteDocumentRowsToMarkLogicTest.java

Ran into this while initially testing triples in document rows. Added test to expose the bug.

Fixing bug with URI generation

---

docs/configuration.md
docs/getting-started/pyspark.md
docs/reading-data/documents.md
docs/writing.md
src/main/java/com/marklogic/spark/Options.java

Not doing the file reading/writing stuff yet.

MLE-12420 Docs for 2.2.0

---

src/main/java/com/marklogic/spark/MarkLogicTable.java
src/main/java/com/marklogic/spark/reader/file/FilePartitionReaderFactory.java
src/main/java/com/marklogic/spark/reader/file/QuadsFileReader.java
src/main/java/com/marklogic/spark/reader/file/RdfErrorHandler.java
src/main/java/com/marklogic/spark/reader/file/RdfSerializer.java
src/test/java/com/marklogic/spark/reader/file/ReadRdfFilesTest.java
src/test/resources/rdf/semantics.nq
src/test/resources/rdf/three-quads.trig

Going to follow this up with a refactor of moving the RDF code into its own package.

MLE-12398 Can now read quads files

---

.gitignore
docs/reading-data/reading-files/aggregate-xml.md
docs/reading-data/reading-files/rdf-data.md
docs/reading-data/reading-files/reading-files.md
docs/reading-data/reading-files/zip-files.md
docs/reading-data/reading.md
examples/getting-started/data/employees.xml

Just doing aggregate XML in this PR. More to come on RDF and ZIP.

MLE-12778 First set of docs for reading files

---

docs/reading-data/reading-files/aggregate-xml.md
docs/reading-data/reading-files/generic-file-support.md
docs/reading-data/reading-files/rdf-data.md
docs/reading-data/reading-files/reading-files.md
docs/reading-data/reading-files/zip-files.md
src/test/java/com/marklogic/spark/reader/file/ReadZipFilesTest.java

MLE-12778 Added docs on generic file stuff and ZIP files

---

docs/configuration.md
docs/reading-data/reading-files/aggregate-xml.md
docs/reading-data/reading-files/rdf-data.md
examples/getting-started/data/quads.trig
examples/getting-started/data/taxonomy.xml
src/test/java/com/marklogic/spark/reader/file/ReadZipFilesTest.java

Will do a separate story for writing files, as well as another story for docs on reading archive files.

MLE-12778 Added rest of docs for reading files

---

src/main/java/com/marklogic/spark/reader/file/FileUtil.java
src/main/java/com/marklogic/spark/writer/file/ZipFileWriter.java
src/test/java/com/marklogic/spark/writer/file/WriteArchiveTest.java

Modified `WriteArchiveTest` to verify properties and metadata values as well, which led to finding my bug in `FileUtil`.

Sonar fixes and fixed bug in FileUtil

---

src/main/java/com/marklogic/spark/reader/file/MlcpArchiveFileReader.java
src/main/java/com/marklogic/spark/reader/file/ZipFileReader.java

No functional change, this is just for consistency.

Tweaking to use IoUtils.closeQuietly

---

src/main/java/com/marklogic/spark/writer/WriteBatcherDataWriter.java
src/main/java/com/marklogic/spark/writer/file/ZipFileWriter.java
src/test/java/com/marklogic/spark/writer/WriteArchiveOfFailedDocumentsTest.java

The issue was that in order to "fail fast" if the user-defined archive path for failed document is invalid, we had to try to create a zip file first. But that results in an empty zip file if no errors occur. Deleting that is problematic, as the user may not have permission to do so, particularly for an S3 path. 
So we no longer fail fast on an invalid user-defined archive path, in favor of avoiding creating empty archive files.

Fixed bug with empty archives being created

---

src/main/java/com/marklogic/spark/reader/file/ArchiveFileReader.java
src/main/java/com/marklogic/spark/reader/file/MlcpArchiveFileReader.java
src/test/java/com/marklogic/spark/reader/file/ReadArchiveFileTest.java
src/test/java/com/marklogic/spark/reader/file/ReadMlcpArchiveFilesTest.java

MLE-13856 Archive URIs no longer include the file path

---

.env
src/main/java/com/marklogic/spark/DefaultSource.java
src/main/java/com/marklogic/spark/Options.java
src/main/java/com/marklogic/spark/reader/document/DocumentBatch.java
src/main/java/com/marklogic/spark/reader/document/DocumentContext.java
src/main/java/com/marklogic/spark/reader/document/DocumentScan.java
src/main/java/com/marklogic/spark/reader/document/DocumentScanBuilder.java
src/main/java/com/marklogic/spark/reader/document/DocumentTable.java
src/main/java/com/marklogic/spark/reader/document/ForestReaderFactory.java
src/main/java/com/marklogic/spark/reader/document/OpticTriplesReader.java
src/test/java/com/marklogic/spark/reader/triples/ReadTriplesTest.java
src/test/ml-data/other-triples/collections.properties
src/test/ml-data/other-triples/other-taxonomy.xml
src/test/ml-data/triples/collections.properties
src/test/ml-data/triples/mini-taxonomy.xml
src/test/ml-modules/options/test-options.xml

Had to modify the `Document` classes to not assume the schema, as both the document row schema and triple row schema are now supported.

MLE-13884 Can now read batches of triples

---

src/main/java/com/marklogic/spark/Options.java
src/main/java/com/marklogic/spark/reader/document/OpticTriplesReader.java
src/test/java/com/marklogic/spark/reader/triples/ReadTriplesWithBaseIriTest.java

Was easier than I thought once I learned of `URI.isAbsolute()`.

ML-13897 Can now apply a base IRI to graph values

---

src/main/java/com/marklogic/spark/MarkLogicFileTable.java
src/main/java/com/marklogic/spark/Options.java
src/main/java/com/marklogic/spark/reader/file/QuadStreamReader.java
src/main/java/com/marklogic/spark/reader/file/RdfSerializer.java
src/main/java/com/marklogic/spark/reader/file/RdfUtil.java
src/main/java/com/marklogic/spark/reader/file/TripleStreamReader.java
src/main/java/com/marklogic/spark/writer/file/DocumentFileBatch.java
src/main/java/com/marklogic/spark/writer/file/DocumentFileWriteBuilder.java
src/main/java/com/marklogic/spark/writer/file/DocumentFileWriterFactory.java
src/main/java/com/marklogic/spark/writer/file/RdfFileWriter.java
src/test/java/com/marklogic/spark/reader/file/ReadRdfFilesTest.java
src/test/java/com/marklogic/spark/writer/file/WriteRdfFilesTest.java

Made some tweaks on the reading side so that we can read in each of the file formats that Jena can stream out.

MLE-13885 Can now write RDF triples to files

---

src/main/java/com/marklogic/spark/ConnectionString.java
src/main/java/com/marklogic/spark/ContextSupport.java
src/test/java/com/marklogic/spark/reader/optic/ReadWithClientUriTest.java

No functional changes, just refactoring.

Extracted connection string validation for reuse in NT

---

CONTRIBUTING.md
build.gradle

Removed some old Gradle tasks that aren't needed and weren't working too.

Simplified CONTRIB

---

src/main/java/com/marklogic/spark/ContextSupport.java
src/main/java/com/marklogic/spark/DefaultSource.java
src/main/java/com/marklogic/spark/Util.java
src/main/java/com/marklogic/spark/reader/optic/OpticReadContext.java
src/main/resources/marklogic-spark-messages.properties

Just a refactoring. Need to be able to override this in Flux.

MLE-14737 Extracted error message for missing Optic query

---

src/main/java/com/marklogic/spark/writer/WriteContext.java

Was only happening when DEBUG was the logging level.

Fixing logging of progress

---

src/main/java/com/marklogic/spark/DefaultSource.java
src/main/java/com/marklogic/spark/reader/customcode/CustomCodePartitionReader.java
src/test/java/com/marklogic/spark/reader/customcode/ReadWithCustomCodeTest.java

Very helpful in debugging. Will expose in Flux too. And trivial to add.

Added progress logging for reading items

---

build.gradle
src/test/java/com/marklogic/spark/reader/document/ReadDocumentRowsByUrisTest.java
src/test/resources/encoding/太田佳伸のＸＭＬファイル.xml

Bumped to Java Client 7.0 to gain the fix for this.

Added test for URI with non-US-ASCII characters

---

build.gradle
src/main/java/com/marklogic/spark/reader/optic/SchemaInferrer.java
src/test/java/com/marklogic/spark/reader/optic/InferSchemaTest.java
src/test/java/com/marklogic/spark/reader/optic/ReadRowsWithInferredSchemaTest.java
src/test/ml-data/allTypes-data.json
src/test/ml-schemas/tde/allTypes.json
src/test/resources/allTypes-columnInfo-response.txt
src/test/resources/allTypes-expected-spark-schema.json

Registered it as a known type so that a warning isn't logged either.

Verifying that collatedString works

---

src/main/java/com/marklogic/spark/reader/file/FileContext.java
src/main/java/com/marklogic/spark/reader/file/FilePartition.java
src/main/java/com/marklogic/spark/reader/file/FilePartitionReaderFactory.java
src/main/java/com/marklogic/spark/reader/file/xml/AggregateXmlFileReader.java
src/main/java/com/marklogic/spark/reader/file/xml/AggregateXmlSplitter.java
src/main/java/com/marklogic/spark/reader/file/xml/ZipAggregateXmlFileReader.java

Had to make some stuff public, but this makes it much easier to see all the aggregate XML code in one place. Will make performance improvement next.

MLE-15791 Refactored aggregate XML classes into a package

---

src/main/java/com/marklogic/spark/reader/file/xml/AggregateXmlSplitter.java
src/main/java/com/marklogic/spark/reader/file/xml/StringHandleWithUriValue.java
src/main/java/com/marklogic/spark/reader/file/xml/UriElementExtractingReader.java
src/main/java/com/marklogic/spark/reader/file/xml/UriElementExtractingVisitor.java
src/test/java/com/marklogic/spark/reader/file/ReadAggregateXmlFilesTest.java
src/test/java/com/marklogic/spark/reader/file/ReadAggregateXmlZipFilesTest.java

Now getting the URI element value while transforming the aggregate element instead of making a second pass.

MLE-15791 Performance improvement for extracting URI element value

---

.gitignore
CONTRIBUTING.md
build.gradle
config/dependency-check-suppressions.xml
docker-compose.yaml

This is something we can repeat in each repository that has Sonarqube setup - which all eventually should.

Added support for detecting dependency vulnerabilities

---

src/main/java/com/marklogic/spark/writer/WriteBatcherDataWriter.java
src/test/java/com/marklogic/spark/reader/file/ReadGenericFilesStreamingTest.java

POST appears to cause issues due to its multipart nature, possibly causing a memory exhaustion error in the server.

MLE-17041 Making PUT call when streaming

---

src/main/java/com/marklogic/spark/writer/file/ContentWriter.java

Sloppy first cut, was still reading the data into a `byte[]`. Still no tests as we'd need a very large file to verify that streaming is occurring. Relying on existing tests and manual verification.

Fix for streaming documents

---

src/main/java/com/marklogic/spark/reader/file/ArchiveFileReader.java
src/main/java/com/marklogic/spark/reader/file/FileContext.java
src/main/java/com/marklogic/spark/reader/file/GenericFileReader.java
src/main/java/com/marklogic/spark/reader/file/GzipFileReader.java
src/main/java/com/marklogic/spark/reader/file/MlcpArchiveFileReader.java
src/main/java/com/marklogic/spark/reader/file/RdfFileReader.java
src/main/java/com/marklogic/spark/reader/file/RdfZipFileReader.java
src/main/java/com/marklogic/spark/reader/file/ZipFileReader.java
src/main/java/com/marklogic/spark/reader/file/xml/AggregateXmlFileReader.java
src/main/java/com/marklogic/spark/reader/file/xml/ZipAggregateXmlFileReader.java
src/test/java/com/marklogic/spark/reader/file/ReadGenericFilesStreamingTest.java
src/test/java/com/marklogic/spark/reader/file/ReadGenericFilesTest.java
src/test/resources/generic-files/with-spaces/hello%20world.json
src/test/resources/generic-files/with-spaces/medline iso 8859 1.txt
src/test/resources/generic-files/with-spaces/three uris.csv

This needs one more change - the streaming test fails because the PUT method rejects spaces in the URI. But wanted to get this 90% solution in place first.

MLE-17084 Initial fix for handling spaces in filenames

---

build.gradle
src/main/java/com/marklogic/spark/Options.java
src/main/java/com/marklogic/spark/writer/DocumentProcessorFactory.java
src/main/java/com/marklogic/spark/writer/WriteBatcherDataWriter.java
src/main/java/com/marklogic/spark/writer/splitter/AllTextSelector.java
src/main/java/com/marklogic/spark/writer/splitter/DefaultChunkAssembler.java
src/test/java/com/marklogic/spark/writer/splitter/SplitTextDocumentTest.java
src/test/java/com/marklogic/spark/writer/splitter/SplitterTest.java
src/test/ml-data/marklogic-docs/java-client-intro.txt

Had to wade a bit into making separate chunk documents in order for this to work. Just did some temporary URI/metadata stuff for now.

MLE-17217 Can now split a text document

---

src/main/java/com/marklogic/spark/Options.java
src/main/java/com/marklogic/spark/writer/DocumentProcessorFactory.java
src/main/java/com/marklogic/spark/writer/splitter/DefaultChunkAssembler.java
src/test/java/com/marklogic/spark/writer/splitter/SplitJsonDocumentTest.java
src/test/java/com/marklogic/spark/writer/splitter/SplitterTest.java

Just adding support for collections/permissions and max chunks for each sidecar document. Will do rootName/namspace and better URIs in separate stories. And XML in a separate story as well.

MLE-1722 Initial support for max chunks per document

---

src/main/java/com/marklogic/spark/writer/splitter/JsonChunkDocumentProducer.java
src/main/java/com/marklogic/spark/writer/splitter/XmlChunkDocumentProducer.java
src/test/java/com/marklogic/spark/writer/splitter/SplitJsonDocumentTest.java
src/test/java/com/marklogic/spark/writer/splitter/SplitXmlDocumentTest.java
src/test/ml-data/marklogic-docs/has-chunks-already.json
src/test/ml-data/marklogic-docs/has-chunks-already.xml

The intent is to avoid another configuration option for a scenario that seems very unlikely to occur.

MLE-17296 Handling when 'chunks' already exists

---

src/main/java/com/marklogic/spark/Options.java
src/main/java/com/marklogic/spark/writer/DocumentProcessorFactory.java
src/test/java/com/marklogic/spark/writer/splitter/SplitXmlDocumentTest.java

Intended to be reused in the upcoming embedder feature.

MLE-17553 Added global XML namespace option

---

src/main/java/com/marklogic/spark/writer/embedding/XmlChunk.java
src/main/java/com/marklogic/spark/writer/splitter/DefaultChunkAssembler.java
src/main/java/com/marklogic/spark/writer/splitter/JDOMTextSelector.java
src/main/java/com/marklogic/spark/writer/splitter/XmlChunkDocumentProducer.java
src/test/java/com/marklogic/spark/writer/embedding/EmbedderTest.java

Just adding the initial XmlChunk support, not tying it into the connector yet. Want to make sure the JDOM/XPath stuff is working first.

MLE-17557 Initial support for XML

---

src/main/java/com/marklogic/spark/Options.java
src/main/java/com/marklogic/spark/writer/embedding/Chunk.java
src/main/java/com/marklogic/spark/writer/embedding/EmbedderDocumentProcessorFactory.java
src/main/java/com/marklogic/spark/writer/embedding/EmbeddingGenerator.java
src/main/java/com/marklogic/spark/writer/embedding/JsonChunk.java
src/main/java/com/marklogic/spark/writer/embedding/JsonChunkSelector.java
src/main/java/com/marklogic/spark/writer/embedding/XmlChunk.java
src/main/java/com/marklogic/spark/writer/embedding/XmlChunkSelector.java
src/main/java/com/marklogic/spark/writer/splitter/JsonChunkDocumentProducer.java
src/main/java/com/marklogic/spark/writer/splitter/XmlChunkDocumentProducer.java
src/main/resources/marklogic-spark-messages.properties
src/test/java/com/marklogic/spark/reader/triples/ReadTriplesTest.java
src/test/java/com/marklogic/spark/writer/embedding/AddEmbeddingsToJsonTest.java
src/test/java/com/marklogic/spark/writer/embedding/AddEmbeddingsToXmlTest.java
src/test/ml-data/marklogic-docs/custom-chunks.xml
src/test/ml-data/marklogic-docs/namespaced-custom-chunks.xml

Had to modify the JSON chunk stuff a bit so that each chunk has its source URI, which is useful for logging.

MLE-17559 Can now customize how embeddings work for XML docs

---

src/main/java/com/marklogic/spark/writer/embedding/DOMChunk.java
src/main/java/com/marklogic/spark/writer/embedding/DOMChunkSelector.java
src/main/java/com/marklogic/spark/writer/embedding/XmlChunkSelector.java
src/test/java/com/marklogic/spark/writer/embedding/DOMChunkSelectorTest.java

Just adding an initial and impl with tests showing how chunk text is selected, which aligns with what John is looking for.
Next PR will drop JDOM2 in favor of DOM.

Verifying that DOM is a better approach for selecting chunks

---

src/main/java/com/marklogic/spark/Options.java
src/main/java/com/marklogic/spark/writer/embedding/EmbedderDocumentProcessor.java
src/main/java/com/marklogic/spark/writer/embedding/EmbedderDocumentProcessorFactory.java
src/main/java/com/marklogic/spark/writer/embedding/EmbeddingGenerator.java
src/main/java/com/marklogic/spark/writer/splitter/SplitterDocumentProcessorFactory.java
src/main/resources/marklogic-spark-messages.properties
src/test/java/com/marklogic/spark/writer/embedding/AddEmbeddingsToJsonTest.java
src/test/java/com/marklogic/spark/writer/embedding/EmbedderTest.java
src/test/java/com/marklogic/spark/writer/embedding/EmbeddingGeneratorTest.java
src/test/java/com/marklogic/spark/writer/embedding/TestEmbeddingModel.java

Going to test this out next on some larger datasets to see what kinds of errors we'll need to handle from the embedding model.

MLE-17715 Can now configure embedder batch size

---

src/main/java/com/marklogic/spark/Options.java
src/main/java/com/marklogic/spark/writer/embedding/EmbeddingGenerator.java

And added some overdue "since" annotations.

Added debug logging for the embedder

---

Jenkinsfile
build.gradle
marklogic-spark-connector/build.gradle

This is close but not there yet. Will bang my head against this again later.

Giving up on multi-project Sonar code coverage for now

---

CONTRIBUTING.md
marklogic-spark-connector/build.gradle
marklogic-spark-connector/src/main/java/com/marklogic/spark/ContextSupport.java
marklogic-spark-connector/src/main/java/com/marklogic/spark/writer/WriteBatcherDataWriter.java
marklogic-spark-connector/src/main/java/com/marklogic/spark/writer/file/ContentWriter.java
marklogic-spark-connector/src/test/java/com/marklogic/spark/AbstractIntegrationTest.java
marklogic-spark-connector/src/test/java/com/marklogic/spark/reader/file/ReadGenericFilesTest.java
marklogic-spark-connector/src/test/java/com/marklogic/spark/reader/file/StreamGenericFilesTest.java
marklogic-spark-connector/src/test/java/com/marklogic/spark/writer/WritePartialBatchTest.java
marklogic-spark-connector/src/test/java/com/marklogic/spark/writer/WriteRowsTest.java
marklogic-spark-connector/src/test/java/com/marklogic/spark/writer/WriteRowsWithTransformTest.java
marklogic-spark-connector/src/test/java/com/marklogic/spark/writer/splitter/BadCustomSplitter.java
marklogic-spark-connector/src/test/java/com/marklogic/spark/writer/splitter/SplitJsonDocumentTest.java

See the comment in WriteBatcherDataWriter. Also fixed a few lingering Sonar issues.

Throw full exception on write failure

---

marklogic-langchain4j/src/main/java/com/marklogic/langchain4j/embedding/XmlChunkConfig.java
marklogic-langchain4j/src/main/java/com/marklogic/langchain4j/splitter/ChunkConfig.java
marklogic-langchain4j/src/main/java/com/marklogic/langchain4j/splitter/XmlChunkDocumentProducer.java
marklogic-spark-connector/src/main/resources/marklogic-spark-messages.properties
marklogic-spark-connector/src/test/java/com/marklogic/spark/AbstractIntegrationTest.java
marklogic-spark-connector/src/test/java/com/marklogic/spark/writer/embedding/AddEmbeddingsToXmlTest.java
marklogic-spark-connector/src/test/java/com/marklogic/spark/writer/splitter/SplitJsonDocumentTest.java
marklogic-spark-langchain4j/src/main/java/com/marklogic/spark/langchain4j/DocumentTextSplitterFactory.java
marklogic-spark-langchain4j/src/main/java/com/marklogic/spark/langchain4j/EmbeddingAdderFactory.java

Also provided a better error message for an invalid max chunk count.

Fix for specifying both namespaces

---

CONTRIBUTING.md
build.gradle
docker-compose.yaml
marklogic-spark-connector/src/main/java/com/marklogic/spark/writer/file/FileUtil.java
marklogic-spark-langchain4j/src/main/java/com/marklogic/spark/langchain4j/DocumentSplitterFactory.java
marklogic-spark-langchain4j/src/main/java/com/marklogic/spark/langchain4j/DocumentTextSplitterFactory.java
marklogic-spark-langchain4j/src/main/java/com/marklogic/spark/langchain4j/EmbeddingAdderFactory.java
marklogic-spark-langchain4j/src/main/java/com/marklogic/spark/langchain4j/NamespaceContextFactory.java

Plus a few existing code smells.

Upgraded Sonar

---

marklogic-spark-connector/src/main/java/com/marklogic/spark/MarkLogicFileTable.java

Realized that it was calling mkdirs when user was trying to read a single file. This was only indicated via logging, so there's no test for this.

MLE-19124 Better check for calling mkdirs

---

marklogic-spark-connector/src/test/java/com/marklogic/spark/reader/optic/PushDownFilterTest.java
marklogic-spark-connector/src/test/java/com/marklogic/spark/reader/optic/PushDownFilterValueTypesTest.java

Want to see if they pass on Jenkins.

Enabling these tests again

---

marklogic-langchain4j/src/main/java/com/marklogic/langchain4j/Util.java
marklogic-langchain4j/src/main/java/com/marklogic/langchain4j/classifier/TextClassifier.java
marklogic-langchain4j/src/main/java/com/marklogic/langchain4j/splitter/JsonChunkDocumentProducer.java
marklogic-langchain4j/src/main/java/com/marklogic/langchain4j/splitter/XmlChunkDocumentProducer.java
marklogic-spark-connector/src/test/java/com/marklogic/spark/writer/classifier/AddConceptsToJsonTest.java
marklogic-spark-connector/src/test/java/com/marklogic/spark/writer/classifier/AddConceptsToXmlTest.java
marklogic-spark-connector/src/test/resources/logback.xml
marklogic-spark-langchain4j/src/main/java/com/marklogic/spark/langchain4j/TextClassifierFactory.java

And made the tests conditional based on an env var so they're a bit easier to test when needed.

Added debug logging for the text classifier

---

marklogic-langchain4j/src/main/java/com/marklogic/langchain4j/Util.java
marklogic-spark-api/src/main/java/com/marklogic/spark/Options.java
marklogic-spark-connector/src/main/java/com/marklogic/spark/reader/document/DocumentRowSchema.java
marklogic-spark-connector/src/main/java/com/marklogic/spark/writer/DocumentRowConverter.java
marklogic-spark-connector/src/main/java/com/marklogic/spark/writer/WriteBatcherDataWriter.java
marklogic-spark-connector/src/main/java/com/marklogic/spark/writer/WriteContext.java
marklogic-spark-connector/src/test/java/com/marklogic/spark/CopyrightTest.java
marklogic-spark-connector/src/test/java/com/marklogic/spark/writer/document/WriteExtractedTextTest.java
marklogic-spark-langchain4j/src/main/java/com/marklogic/spark/langchain4j/NamespaceContextFactory.java

Going with a simple document with a single "content" field for now. Going to test how this holds up with the splitter / classifier / embedder.

MLE-19647 Can now extract text to JSON or XML

---

marklogic-langchain4j/src/main/java/com/marklogic/langchain4j/splitter/ChunkAssembler.java
marklogic-langchain4j/src/main/java/com/marklogic/langchain4j/splitter/DefaultChunkAssembler.java
marklogic-langchain4j/src/main/java/com/marklogic/langchain4j/splitter/JsonPointerTextSelector.java
marklogic-langchain4j/src/main/java/com/marklogic/langchain4j/splitter/TextSelector.java
marklogic-spark-connector/src/main/java/com/marklogic/spark/udf/TextSplitter.java
marklogic-spark-connector/src/main/java/com/marklogic/spark/writer/DocBuilder.java
marklogic-spark-connector/src/main/java/com/marklogic/spark/writer/DocBuilderFactory.java
marklogic-spark-connector/src/main/java/com/marklogic/spark/writer/WriteBatcherDataWriter.java
marklogic-spark-connector/src/main/java/com/marklogic/spark/writer/WriteContext.java
marklogic-spark-connector/src/main/java/com/marklogic/spark/writer/document/DocumentRow.java
marklogic-spark-connector/src/main/java/com/marklogic/spark/writer/document/DocumentRowConverter.java
marklogic-spark-connector/src/test/java/com/marklogic/spark/writer/document/WriteExtractedTextTest.java
marklogic-spark-connector/src/test/java/com/marklogic/spark/writer/splitter/SplitJsonDocumentTest.java
marklogic-spark-langchain4j/src/main/java/com/marklogic/spark/langchain4j/DocumentTextSplitterFactory.java

This is just a first step. Just proving the approach works. Will need to add all the splitter options to the UDF.

Can now split via a UDF

---

marklogic-spark-connector/src/main/java/com/marklogic/spark/udf/TextClassifierUdf.java

Also moved token generation into the classifyText function so that configuration could be tested without generating a token.

Made the classifier UDF configuration viewable.

---

marklogic-spark-connector/src/main/java/com/marklogic/spark/reader/file/RdfSerializer.java
marklogic-spark-connector/src/test/java/com/marklogic/spark/reader/file/ReadRdfFilesTest.java
marklogic-spark-connector/src/test/resources/rdf/multiple-blank-nodes.ttl

Using Jena's existing support for generating a unique and consistent blank node ID.

MLE-19758 Fixing blank node ID generation

---

.gitignore
CONTRIBUTING.md
build.gradle
marklogic-langchain4j/build.gradle
marklogic-spark-api/build.gradle
marklogic-spark-api/src/main/java/com/marklogic/spark/Options.java
marklogic-spark-connector/build.gradle
marklogic-spark-connector/src/main/java/com/marklogic/spark/writer/DocumentProcessorFactory.java
tests/build.gradle

Testing this out in Flux, it looks like it should work fine.

Bumping LangChain4j so that it requires Java 17

---

build.gradle
marklogic-langchain4j/src/main/java/com/marklogic/langchain4j/embedding/EmbeddingAdder.java
marklogic-langchain4j/src/main/java/com/marklogic/langchain4j/embedding/EmbeddingAdderFactory.java
marklogic-langchain4j/src/main/java/com/marklogic/langchain4j/embedding/EmbeddingGenerator.java
marklogic-langchain4j/src/main/java/com/marklogic/langchain4j/splitter/DocumentTextSplitter.java
marklogic-langchain4j/src/main/java/com/marklogic/spark/udf/TextSplitter.java
marklogic-spark-connector/src/main/java/com/marklogic/spark/reader/document/DocumentTable.java
marklogic-spark-connector/src/main/java/com/marklogic/spark/udf/TextClassifierUdf.java
marklogic-spark-connector/src/main/java/com/marklogic/spark/writer/DocumentProcessorFactory.java
marklogic-spark-connector/src/main/java/com/marklogic/spark/writer/FileRowConverter.java
marklogic-spark-connector/src/main/java/com/marklogic/spark/writer/WriteBatcherDataWriter.java
marklogic-spark-connector/src/main/java/com/marklogic/spark/writer/WriteContext.java

Also ignored several compiler warnings that we can't do anything about.

Fixing Sonar warnings related to Java 17

---

marklogic-spark-connector/src/main/java/com/marklogic/spark/writer/NewDocumentProcessor.java
marklogic-spark-connector/src/main/java/com/marklogic/spark/writer/NewDocumentProcessorFactory.java
marklogic-spark-connector/src/main/java/com/marklogic/spark/writer/WriteBatcherDataWriter.java
marklogic-spark-connector/src/main/java/com/marklogic/spark/writer/document/DocumentRowConverter.java

This will be the eventual home for all the processing code.

Refactor: Move extraction code into new processor

---

marklogic-langchain4j/src/main/java/com/marklogic/langchain4j/splitter/DocumentTextSplitter.java
marklogic-langchain4j/src/main/java/com/marklogic/spark/langchain4j/Langchain4jDocumentProcessorFactory.java
marklogic-spark-api/src/main/java/com/marklogic/spark/core/splitter/TextSelector.java
marklogic-spark-api/src/main/java/com/marklogic/spark/core/splitter/TextSplitter.java
marklogic-spark-api/src/main/java/com/marklogic/spark/core/splitter/TextSplitterFactory.java
marklogic-spark-connector/src/main/java/com/marklogic/spark/writer/DocumentProcessorFactory.java
marklogic-spark-connector/src/main/java/com/marklogic/spark/writer/NewDocumentProcessor.java
marklogic-spark-connector/src/main/java/com/marklogic/spark/writer/NewDocumentProcessorFactory.java

Next up is supporting splitting w/ embedding and classifying.
Trying to layer the new stuff on top of the old stuff so old stuff can be reused. Will then delete some old stuff once all new stuff works.

Refactor: Some splitting now goes through new processor

---

marklogic-langchain4j/src/main/java/com/marklogic/langchain4j/embedding/EmbeddingAdderFactory.java
marklogic-langchain4j/src/main/java/com/marklogic/langchain4j/embedding/EmbeddingGenerator.java
marklogic-langchain4j/src/main/java/com/marklogic/spark/langchain4j/Langchain4jDocumentProcessorFactory.java
marklogic-spark-api/src/main/java/com/marklogic/spark/core/embedding/EmbeddingProducer.java
marklogic-spark-api/src/main/java/com/marklogic/spark/core/embedding/EmbeddingProducerFactory.java
marklogic-spark-api/src/main/java/com/marklogic/spark/core/splitter/DefaultChunkAssembler.java
marklogic-spark-connector/src/main/java/com/marklogic/spark/writer/DocBuilder.java
marklogic-spark-connector/src/main/java/com/marklogic/spark/writer/DocumentProcessorFactory.java
marklogic-spark-connector/src/main/java/com/marklogic/spark/writer/NewDocumentProcessor.java
marklogic-spark-connector/src/main/java/com/marklogic/spark/writer/NewDocumentProcessorFactory.java
marklogic-spark-connector/src/main/java/com/marklogic/spark/writer/WriteBatcherDataWriter.java
tests/src/test/java/com/marklogic/spark/writer/embedding/AddEmbeddingsToJsonTest.java
tests/src/test/java/com/marklogic/spark/writer/embedding/AddEmbeddingsToXmlTest.java

Two things that aren't working yet - adding embeddings when not splitting text, and the embedder batch size. Two more PRs coming to address those.

Refactor: Some of the embedder now works through new processor

---

marklogic-langchain4j/src/main/java/com/marklogic/langchain4j/embedding/EmbeddingAdderFactory.java
marklogic-spark-api/src/main/java/com/marklogic/spark/core/embedding/ChunkSelector.java
marklogic-spark-api/src/main/java/com/marklogic/spark/core/embedding/ChunkSelectorFactory.java
marklogic-spark-api/src/main/java/com/marklogic/spark/core/embedding/DOMChunkSelector.java
marklogic-spark-api/src/main/java/com/marklogic/spark/core/embedding/JsonChunkSelector.java
marklogic-spark-connector/src/main/java/com/marklogic/spark/writer/DocBuilder.java
marklogic-spark-connector/src/main/java/com/marklogic/spark/writer/NewDocumentProcessor.java
marklogic-spark-connector/src/main/java/com/marklogic/spark/writer/NewDocumentProcessorFactory.java
tests/src/test/java/com/marklogic/spark/writer/embedding/AddEmbeddingsToJsonTest.java
tests/src/test/java/com/marklogic/spark/writer/embedding/AddEmbeddingsToXmlTest.java

Next up - embedder batch size.

Refactor: New embedder now supports existing chunks

---

marklogic-spark-api/src/main/java/com/marklogic/spark/core/DocumentInputs.java
marklogic-spark-connector/src/main/java/com/marklogic/spark/writer/ArbitraryRowConverter.java
marklogic-spark-connector/src/main/java/com/marklogic/spark/writer/DocBuilder.java
marklogic-spark-connector/src/main/java/com/marklogic/spark/writer/FileRowConverter.java
marklogic-spark-connector/src/main/java/com/marklogic/spark/writer/NewDocumentProcessor.java
marklogic-spark-connector/src/main/java/com/marklogic/spark/writer/RowConverter.java
marklogic-spark-connector/src/main/java/com/marklogic/spark/writer/WriteBatcherDataWriter.java
marklogic-spark-connector/src/main/java/com/marklogic/spark/writer/document/DocumentRowConverter.java
marklogic-spark-connector/src/main/java/com/marklogic/spark/writer/file/ArchiveFileIterator.java
marklogic-spark-connector/src/main/java/com/marklogic/spark/writer/file/FileIterator.java
marklogic-spark-connector/src/main/java/com/marklogic/spark/writer/file/GzipFileIterator.java
marklogic-spark-connector/src/main/java/com/marklogic/spark/writer/file/ZipFileIterator.java
marklogic-spark-connector/src/main/java/com/marklogic/spark/writer/rdf/RdfRowConverter.java
marklogic-spark-connector/src/main/java/com/marklogic/spark/writer/rdf/TriplesDocument.java

Need this to be in the "core" project so that the langchain4j-specific embedder can access it for batching purposes.
Expecting DocBuilder to eventually go into the core projet as well.

Refactor: Moved DocumentInputs

---

build.gradle

Sonar isn't picking up the coverage data correctly yet due to our multi-project build.

Draft: Seeing if this turns off coverage verification

---

gradle.properties
marklogic-spark-api/build.gradle
marklogic-spark-api/src/main/java/com/marklogic/spark/core/DocumentProcessor.java
marklogic-spark-api/src/main/java/com/marklogic/spark/core/classifier/SemaphoreTextClassifier.java
marklogic-spark-api/src/main/java/com/marklogic/spark/core/classifier/TextClassifier.java
marklogic-spark-api/src/main/java/com/marklogic/spark/core/classifier/TextClassifierFactory.java
marklogic-spark-connector/src/main/java/com/marklogic/spark/writer/WriteBatcherDataWriter.java
tests/build.gradle
tests/src/test/java/com/marklogic/spark/reader/file/ReadMlcpArchiveFilesTest.java
tests/src/test/java/com/marklogic/spark/reader/optic/ReadRowsWithInferredSchemaTest.java
tests/src/test/java/com/marklogic/spark/writer/WriteRowsWithUriTemplateTest.java
tests/src/test/java/com/marklogic/spark/writer/classifier/AddClassificationToJsonTest.java
tests/src/test/java/com/marklogic/spark/writer/classifier/AddClassificationToXmlTest.java
tests/src/test/java/com/marklogic/spark/writer/document/WriteExtractedTextTest.java
tests/src/test/java/com/marklogic/spark/writer/file/WriteRdfFilesTest.java

Also removed some rogue System.out calls, and added a Gradle property for the Tika version.

Ensuring that the connection to S4 is closed

---

marklogic-spark-connector/src/main/java/com/marklogic/spark/writer/DocBuilder.java
tests/src/test/java/com/marklogic/spark/writer/document/WriteExtractedTextTest.java

This allows for directory-query to be used.

Adjusting extracted text URI

---

marklogic-spark-api/src/main/java/com/marklogic/spark/core/DocumentInputs.java
marklogic-spark-api/src/main/java/com/marklogic/spark/core/DocumentPipeline.java
marklogic-spark-api/src/main/java/com/marklogic/spark/core/classifier/MultiArticleClassifier.java
marklogic-spark-api/src/main/java/com/marklogic/spark/core/classifier/SemaphoreMultiArticleClassifier.java
marklogic-spark-api/src/main/java/com/marklogic/spark/core/classifier/SemaphoreTextClassifier.java
marklogic-spark-api/src/main/java/com/marklogic/spark/core/classifier/TextClassifier.java
marklogic-spark-api/src/main/java/com/marklogic/spark/core/classifier/TextClassifierFactory.java
marklogic-spark-api/src/main/java/com/marklogic/spark/core/extraction/TikaTextExtractor.java
marklogic-spark-connector/src/main/java/com/marklogic/spark/writer/DocBuilder.java
tests/src/test/java/com/marklogic/spark/writer/classifier/AddClassificationToJsonTest.java
tests/src/test/java/com/marklogic/spark/writer/classifier/AddClassificationToXmlTest.java
tests/src/test/java/com/marklogic/spark/writer/classifier/ClassifierTestUtil.java
tests/src/test/java/com/marklogic/spark/writer/classifier/ClassifyExtractedTextTest.java

Got some renaming to do after this - i.e. `MultiArticleClassifier` doesn't make any sense now. Will do a renaming refactor after this is merged in.

MLE-21194 Now classifying original doc with single article request

---

docker-compose.yaml
marklogic-spark-connector/src/main/java/com/marklogic/spark/ProgressLogger.java
marklogic-spark-connector/src/main/java/com/marklogic/spark/ReadProgressLogger.java
marklogic-spark-connector/src/main/java/com/marklogic/spark/WriteProgressLogger.java
marklogic-spark-connector/src/main/java/com/marklogic/spark/reader/document/OpticTriplesReader.java

Hoping I finally got synchronized logging working without Polaris complaining.

Fixing a few high Polaris issues

---

NOTICE.txt
docs/getting-started/jupyter.md
docs/getting-started/pyspark.md
docs/getting-started/setup.md
examples/entity-aggregation/build.gradle
examples/getting-started/marklogic-spark-getting-started.ipynb
examples/java-dependency/build.gradle

Also bumped reference to version in docs. Will bump actual version on release branch.

Updated NOTICE file for 2.6.0

---

NOTICE.txt
marklogic-langchain4j/build.gradle
tests/build.gradle

Just keeping up with the Jones's.

Bumping langchain4j to latest version

---

marklogic-spark-api/src/main/java/com/marklogic/spark/core/ServerEvaluationCallFactory.java
marklogic-spark-connector/src/main/java/com/marklogic/spark/ContextSupport.java
marklogic-spark-connector/src/main/java/com/marklogic/spark/reader/customcode/CustomCodeContext.java
marklogic-spark-connector/src/main/java/com/marklogic/spark/reader/customcode/CustomCodePartitionReader.java
marklogic-spark-connector/src/main/java/com/marklogic/spark/reader/customcode/CustomCodeScan.java
marklogic-spark-connector/src/main/java/com/marklogic/spark/reader/customcode/CustomCodeScanBuilder.java
marklogic-spark-connector/src/main/java/com/marklogic/spark/writer/MarkLogicWrite.java
marklogic-spark-connector/src/main/java/com/marklogic/spark/writer/customcode/CustomCodeWriter.java
tests/src/test/java/com/marklogic/spark/reader/customcode/SerializeCustomCodeReaderTest.java
tests/src/test/java/com/marklogic/spark/writer/customcode/SerializeCustomCodeWriterTest.java

No change in functionality. Wanted to extract the resuable logic for builing a ServerEvaluationCall out of CustomCodeContext so it's easier to understand and reuse.

MLE-21726 Refactor: Extracted ServerEvaluationCallFactory

---

build.gradle
gradle.properties
marklogic-spark-connector/build.gradle
marklogic-spark-connector/src/main/java/com/marklogic/spark/DefaultSource.java
marklogic-spark-connector/src/main/java/com/marklogic/spark/JsonRowSerializer.java
marklogic-spark-connector/src/main/java/com/marklogic/spark/MarkLogicFileTable.java
marklogic-spark-connector/src/main/java/com/marklogic/spark/reader/JsonRowDeserializer.java
marklogic-spark-connector/src/main/java/com/marklogic/spark/reader/document/OpticTriplesReader.java
marklogic-spark-connector/src/main/java/com/marklogic/spark/reader/file/RdfZipFileReader.java
marklogic-spark-connector/src/main/java/com/marklogic/spark/writer/file/ContentWriter.java
tests/build.gradle
tests/src/test/java/com/marklogic/spark/AbstractIntegrationTest.java
tests/src/test/java/com/marklogic/spark/reader/document/ReadDocumentRowsWithMetadataTest.java
tests/src/test/java/com/marklogic/spark/reader/file/ReadArchiveFileTest.java
tests/src/test/java/com/marklogic/spark/reader/file/ReadMlcpArchiveFilesTest.java
tests/src/test/java/com/marklogic/spark/reader/optic/AbstractPushDownTest.java
tests/src/test/java/com/marklogic/spark/reader/optic/GroupByDuplicateColumnNamesTest.java
tests/src/test/java/com/marklogic/spark/writer/WriteArchiveOfFailedDocumentsTest.java
tests/src/test/java/com/marklogic/spark/writer/WriteStreamOfRowsTest.java

Merging this to a 4.0-specific branch, not develop. Just want to get this in place as verification that it's not a difficult upgrade to Spark 4.

MLE-23024 Building against Spark 4

---

Jenkinsfile
build.gradle
gradle.properties
marklogic-langchain4j/build.gradle
tests/build.gradle

This will help with some Azure/Netty stuff in Flux.

MLE-23170 Bumping langchain to latest version

---

docs/reading-data/documents.md
docs/writing.md

Copilot generated the content for the new "secondary URIs" feature.

MLE-22951 Added docs for new connector features

---

marklogic-spark-api/src/main/java/com/marklogic/spark/Experimental.java
marklogic-spark-api/src/main/java/com/marklogic/spark/Options.java
marklogic-spark-connector/src/main/java/com/marklogic/spark/DefaultSource.java
marklogic-spark-connector/src/main/java/com/marklogic/spark/reader/filter/IsNotNullFilter.java
marklogic-spark-connector/src/main/java/com/marklogic/spark/reader/filter/IsNullFilter.java
marklogic-spark-connector/src/main/java/com/marklogic/spark/reader/filter/OpticFilter.java
marklogic-spark-connector/src/main/java/com/marklogic/spark/reader/filter/SingleValueFilter.java
marklogic-spark-connector/src/main/java/com/marklogic/spark/reader/optic/OpticReadContext.java
tests/src/test/java/com/marklogic/spark/reader/optic/ReadRowsWithParamsTest.java

Experimental feature for now. But works per the test cases.

MLE-17124 Added support for pushing filter values to Optic params
